/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "callback_USART2_IRQHandler.h"

void callback_USART2_IRQHandler(const int64_t *n_var0)
{
    emitter_USART2_IRQHandler(n_var0);
}
