/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __CALLBACK_20MS_H__
#define __CALLBACK_20MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <smaccm_thread_period_20ms.h>
void callback_20ms(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __CALLBACK_20MS_H__ */
