/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __I2C1PERIPHERALDRIVER_MONITOR_H__
#define __I2C1PERIPHERALDRIVER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2cTowerTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_i2c1PeripheralDriver.h>
#include <ivory_hw_prim.h>
extern uint8_t i2c1_driverstate;
extern bool i2c1_ready_sent;
extern struct i2c_transaction_request i2c1_reqbuffer;
extern int32_t i2c1_reqbufferpos;
extern struct i2c_transaction_result i2c1_resbuffer;
extern int32_t i2c1_resbufferpos;
extern uint32_t i2c1_invalid_request;
extern uint32_t i2c1_error_run;
extern int64_t i2c1_last_event;
void callback_i2c1_init(const int64_t *n_var0);
void callback_i2c1_ready_period(const int64_t *n_var0);
void callback_i2c1_watchdog(const int64_t *n_var0);
void callback_i2c1_error_irq(const int64_t *n_var0);
void callback_i2c1_event_irq(const int64_t *n_var0);
void callback_i2c1_request(const struct i2c_transaction_request *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __I2C1PERIPHERALDRIVER_MONITOR_H__ */
