/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __I2C1_EV_IRQHANDLER_H__
#define __I2C1_EV_IRQHANDLER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2c1PeripheralDriver_monitor.h"
#include "simplecontroller_monitor.h"
#include "callback_I2C1_ER_IRQHandler.h"
#include "callback_I2C1_EV_IRQHandler.h"
#include "callback_1ms.h"
#include "callback_20ms.h"
#include "callback_250ms.h"
#include "callback_systemInit.h"
void I2C1_EV_IRQHandler(void);

#ifdef __cplusplus
}
#endif
#endif /* __I2C1_EV_IRQHANDLER_H__ */
