/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __SIMPLECONTROLLER_MONITOR_H__
#define __SIMPLECONTROLLER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2cTowerTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_simplecontroller.h>
void callback_periodic(const int64_t *n_var0);
void callback_result(const struct i2c_transaction_result *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __SIMPLECONTROLLER_MONITOR_H__ */
