/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_USER_THREAD_PERIOD_1MS_H__
#define __TOWER_USER_THREAD_PERIOD_1MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "spiDriverTypes.h"
#include "tower_state_monitor_spi4PeripheralDriver.h"
#include "tower_state_monitor_simplecontroller.h"
#include "tower_gen_thread_period_1ms.h"
#include "tower_time.h"
void callback_result_thread_period_1ms(const struct spi_transaction_result *n_var0);
void callback_spi_shutdown_watchdog_thread_period_1ms(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_USER_THREAD_PERIOD_1MS_H__ */
