/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_init.h"

void callback_initialize_hardware_thread_init(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887300U);
    
    /* reg modify rcc_apb2enr: setBit rcc_apb2en_spi4 */
    ivory_hw_io_write_u32((uint32_t) 1073887300U, (uint32_t) (n_r0 | (uint32_t) ((uint32_t) 1U << (uint32_t) 13U)));
    
    uint16_t n_r1 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: clearBit spi_cr1_bidimode, clearBit spi_cr1_bidioe, clearBit spi_cr1_crcen, clearBit spi_cr1_crcnext, clearBit spi_cr1_dff, clearBit spi_cr1_rxonly, clearBit spi_cr1_ssm, clearBit spi_cr1_ssi, clearBit spi_cr1_lsbfirst, clearBit spi_cr1_spe, setField spi_cr1_br, clearBit spi_cr1_mstr, clearBit spi_cr1_cpol, clearBit spi_cr1_cpha */
    ;
    
    uint16_t n_cse29 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U);
    uint16_t n_cse32 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U);
    uint16_t n_cse41 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U);
    uint16_t n_cse44 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U);
    uint16_t n_cse47 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << 0);
    
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_r1 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                             (uint16_t) 13U)) &
                                                                                                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) &
                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U)) & n_cse29) & n_cse32) & (uint16_t) ~(uint16_t) ((uint16_t) 7U << (uint16_t) 3U)) | (uint16_t) (0 << (uint16_t) 3U)) &
                                                                                      n_cse41) & n_cse44) & n_cse47));
    
    uint16_t n_r2 = ivory_hw_io_read_u16((uint32_t) 1073820676U);
    
    /* reg modify spi4->cr2: clearBit spi_cr2_txeie, clearBit spi_cr2_rxneie, clearBit spi_cr2_errie, clearBit spi_cr2_ssoe, clearBit spi_cr2_txdmaen, clearBit spi_cr2_rxdmaen */
    ivory_hw_io_write_u16((uint32_t) 1073820676U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_cse47 & n_cse44) & n_cse41) & n_cse32) & n_cse29) & n_r2) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 5U)));
    /* init spi input pin gpioE5 */
    ;
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ;
    
    uint32_t n_cse59 = (uint32_t) ((uint32_t) 1U << (uint32_t) 4U);
    
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_r3 | n_cse59));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073877024U);
    
    /* reg modify gpioE->afrl: setField gpio_afrl_5 */
    ;
    
    uint32_t n_cse67 = (uint32_t) (uint8_t) ((uint8_t) 5U << 0);
    
    ivory_hw_io_write_u32((uint32_t) 1073877024U, (uint32_t) ((uint32_t) (n_r4 & (uint32_t) ~(uint32_t) ((uint32_t) 15U << (uint32_t) 20U)) | (uint32_t) (n_cse67 << (uint32_t) 20U)));
    
    uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_5 */
    ;
    
    uint32_t n_cse72 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 10U);
    uint32_t n_cse76 = (uint32_t) (uint8_t) ((uint8_t) 2U << 0);
    uint32_t n_cse77 = (uint32_t) (n_cse76 << (uint32_t) 10U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r5 & n_cse72) | n_cse77));
    
    uint32_t n_r6 = ivory_hw_io_read_u32((uint32_t) 1073877004U);
    
    /* reg modify gpioE->pupd: setField gpio_pupd_5 */
    ivory_hw_io_write_u32((uint32_t) 1073877004U, (uint32_t) ((uint32_t) (n_cse72 & n_r6) | (uint32_t) (0 << (uint32_t) 10U)));
    
    uint32_t n_r7 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_5 */
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) (n_cse77 | (uint32_t) (n_cse72 & n_r7)));
    /* init spi output pin gpioE6 */
    ;
    
    uint32_t n_r8 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse59 | n_r8));
    
    uint32_t n_r9 = ivory_hw_io_read_u32((uint32_t) 1073877024U);
    
    /* reg modify gpioE->afrl: setField gpio_afrl_6 */
    ivory_hw_io_write_u32((uint32_t) 1073877024U, (uint32_t) ((uint32_t) (n_r9 & (uint32_t) ~(uint32_t) ((uint32_t) 15U << (uint32_t) 24U)) | (uint32_t) (n_cse67 << (uint32_t) 24U)));
    
    uint32_t n_r10 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_6 */
    ;
    
    uint32_t n_cse97 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 12U);
    uint32_t n_cse99 = (uint32_t) (n_cse76 << (uint32_t) 12U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r10 & n_cse97) | n_cse99));
    
    uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_6 */
    ;
    
    uint32_t n_cse105 = (uint32_t) (0 << (uint32_t) 6U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) ((uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 6U) & n_r11) | n_cse105));
    
    uint32_t n_r12 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_6 */
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) (n_cse99 | (uint32_t) (n_cse97 & n_r12)));
    /* init spi output pin gpioE2 */
    ;
    
    uint32_t n_r13 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse59 | n_r13));
    
    uint32_t n_r14 = ivory_hw_io_read_u32((uint32_t) 1073877024U);
    
    /* reg modify gpioE->afrl: setField gpio_afrl_2 */
    ivory_hw_io_write_u32((uint32_t) 1073877024U, (uint32_t) ((uint32_t) (n_r14 & (uint32_t) ~(uint32_t) ((uint32_t) 15U << (uint32_t) 8U)) | (uint32_t) (n_cse67 << (uint32_t) 8U)));
    
    uint32_t n_r15 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_2 */
    ;
    
    uint32_t n_cse120 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 4U);
    uint32_t n_cse122 = (uint32_t) (n_cse76 << (uint32_t) 4U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r15 & n_cse120) | n_cse122));
    
    uint32_t n_r16 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_2 */
    ;
    
    uint32_t n_cse124 = (uint32_t) ((uint32_t) 1U << (uint32_t) 2U);
    uint32_t n_cse125 = (uint32_t) ~n_cse124;
    uint32_t n_cse128 = (uint32_t) (0 << (uint32_t) 2U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) (n_cse125 & n_r16) | n_cse128));
    
    uint32_t n_r17 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_2 */
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) (n_cse122 | (uint32_t) (n_cse120 & n_r17)));
    
    uint32_t n_r18 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse59 | n_r18));
    
    uint32_t n_r19 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
    
    /* reg modify gpioE->bsrr: setBit gpio_bs_2 */
    ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_cse124 | n_r19));
    
    uint32_t n_r20 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_2 */
    ;
    
    uint32_t n_cse141 = (uint32_t) (uint8_t) ((uint8_t) 1U << 0);
    
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_cse120 & n_r20) | (uint32_t) (n_cse141 << (uint32_t) 4U)));
    
    uint32_t n_r21 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_2 */
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) (n_cse128 | (uint32_t) (n_cse125 & n_r21)));
    
    uint32_t n_r22 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_2 */
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) ((uint32_t) (n_cse120 & n_r22) | (uint32_t) (0 << (uint32_t) 4U)));
    
    uint32_t n_r23 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse59 | n_r23));
    
    uint32_t n_r24 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
    
    /* reg modify gpioE->bsrr: setBit gpio_bs_3 */
    ;
    
    uint32_t n_cse154 = (uint32_t) ((uint32_t) 1U << (uint32_t) 3U);
    
    ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r24 | n_cse154));
    
    uint32_t n_r25 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_3 */
    ;
    
    uint32_t n_cse158 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 6U);
    
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r25 & n_cse158) | (uint32_t) (n_cse141 << (uint32_t) 6U)));
    
    uint32_t n_r26 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_3 */
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) (0 << (uint32_t) 3U) | (uint32_t) (n_r26 & (uint32_t) ~n_cse154)));
    
    uint32_t n_r27 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_3 */
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) (n_cse105 | (uint32_t) (n_cse158 & n_r27)));
    done = true;
    /* reg set nvic_iser2: setBit nvic_iser_setena.[20] */
    ivory_hw_io_write_u32((uint32_t) 3758153992U, (uint32_t) ((uint32_t) 1U << (uint32_t) 20U));
}
