/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_THREAD_INIT_H__
#define __TOWER_GEN_THREAD_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "spiDriverTypes.h"
#include "tower_user_thread_init.h"
#include "tower_gen_monitor_spi4PeripheralDriver.h"
#include <freertos_time_wrapper.h>
void loop_thread_init(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_THREAD_INIT_H__ */
