/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_spi4PeripheralDriver.h"

bool done;

bool shutdown = false;

struct spi_transaction_request reqbuffer;

int32_t reqbufferpos;

struct spi_transaction_result resbuffer;

int32_t resbufferpos;

void testdevice1_250khz_pinE2_devicebegin(void)
{
    uint16_t n_r0 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: clearBit spi_cr1_spe */
    ;
    
    uint16_t n_cse1 = (uint16_t) ((uint16_t) 1U << (uint16_t) 6U);
    
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) (n_r0 & (uint16_t) ~n_cse1));
    
    uint16_t n_r1 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: setBit spi_cr1_mstr, setBit spi_cr1_ssm, setBit spi_cr1_ssi, setField spi_cr1_br, clearBit spi_cr1_cpol, clearBit spi_cr1_cpha, clearBit spi_cr1_lsbfirst */
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_r1 | (uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 8U)) & (uint16_t) ~(uint16_t) ((uint16_t) 7U << (uint16_t) 3U)) |
                                                                                                  (uint16_t) ((uint16_t) (uint8_t) ((uint8_t) 7U << 0) << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << 0)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)));
    
    uint16_t n_r2 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: setBit spi_cr1_spe */
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) (n_cse1 | n_r2));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
    
    /* reg modify gpioE->bsrr: setBit gpio_br_2 */
    ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r3 | (uint32_t) ((uint32_t) 1U << (uint32_t) 18U)));
}

void testdevice2_500khz_pinE3_devicebegin(void)
{
    uint16_t n_r0 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: clearBit spi_cr1_spe */
    ;
    
    uint16_t n_cse1 = (uint16_t) ((uint16_t) 1U << (uint16_t) 6U);
    
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) (n_r0 & (uint16_t) ~n_cse1));
    
    uint16_t n_r1 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: setBit spi_cr1_mstr, setBit spi_cr1_ssm, setBit spi_cr1_ssi, setField spi_cr1_br, clearBit spi_cr1_cpol, clearBit spi_cr1_cpha, clearBit spi_cr1_lsbfirst */
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_r1 | (uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 8U)) & (uint16_t) ~(uint16_t) ((uint16_t) 7U << (uint16_t) 3U)) |
                                                                                                  (uint16_t) ((uint16_t) (uint8_t) ((uint8_t) 7U << 0) << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << 0)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)));
    
    uint16_t n_r2 = ivory_hw_io_read_u16((uint32_t) 1073820672U);
    
    /* reg modify spi4->cr1: setBit spi_cr1_spe */
    ivory_hw_io_write_u16((uint32_t) 1073820672U, (uint16_t) (n_cse1 | n_r2));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
    
    /* reg modify gpioE->bsrr: setBit gpio_br_3 */
    ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r3 | (uint32_t) ((uint32_t) 1U << (uint32_t) 19U)));
}
