/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_MONITOR_SPI4PERIPHERALDRIVER_H__
#define __TOWER_GEN_MONITOR_SPI4PERIPHERALDRIVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "spiDriverTypes.h"
#include <freertos_mutex_wrapper.h>
extern struct mutex lock_spi4PeripheralDriver;
void monitor_init_spi4PeripheralDriver(void);
void monitor_lock_spi4PeripheralDriver(void);
void monitor_unlock_spi4PeripheralDriver(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_MONITOR_SPI4PERIPHERALDRIVER_H__ */
