/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_250ms.h"

static void emitter_periodic_chan_1(const struct spi_transaction_request *n_var0);

void callback_periodic_thread_period_250ms(const int64_t *n_var0)
{
    int64_t n_deref0 = *n_var0;
    int64_t n_cse0 = (int64_t) (n_deref0 % (int64_t) 500000);
    
    if ((bool) ((int64_t) ((bool) (n_cse0 < (int64_t) 0) ? (int64_t) (n_cse0 + (int64_t) 500000) : n_cse0) >= (int64_t) 250000)) {
        struct spi_transaction_request n_local1 = {.tx_device =(uint8_t) 0U, .tx_buf ={(uint8_t) 241U, (uint8_t) 242U, (uint8_t) 243U}, .tx_len =(int32_t) 3};
        struct spi_transaction_request *n_ref2 = &n_local1;
        
        emitter_periodic_chan_1(n_ref2);
    } else {
        struct spi_transaction_request n_local3 = {.tx_device =(uint8_t) 1U, .tx_buf ={(uint8_t) 244U, (uint8_t) 245U, (uint8_t) 246U, (uint8_t) 247U}, .tx_len =(int32_t) 4};
        struct spi_transaction_request *n_ref4 = &n_local3;
        
        emitter_periodic_chan_1(n_ref4);
    }
}

void callback_request_thread_period_250ms(const struct spi_transaction_request *n_var0)
{
    bool n_deref0 = done;
    
    if (n_deref0) {
        done = false;
        reqbuffer = *n_var0;
        
        int32_t n_deref1 = reqbuffer.tx_len;
        
        reqbufferpos = (int32_t) 0;
        resbufferpos = (int32_t) 0;
        resbuffer.rx_idx = n_deref1;
        
        uint8_t n_deref2 = reqbuffer.tx_buf[(int32_t) 0];
        
        reqbufferpos = (int32_t) 1;
        /* selecting device: */
        ;
        
        uint8_t n_deref3 = reqbuffer.tx_device;
        
        ASSERTS((bool) (n_deref3 < (uint8_t) 2U));
        if ((bool) (0 == n_deref3)) {
            testdevice1_250khz_pinE2_devicebegin();
        } else {
            if ((bool) ((uint8_t) 1U == n_deref3)) {
                testdevice2_500khz_pinE3_devicebegin();
            }
        }
        /* end selecting configured device */
        ;
        /* reg set spi4->dr: setField spi_dr_data */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073820684U, (uint16_t) ((uint16_t) n_deref2 << 0));
        
        uint16_t n_r4 = ivory_hw_io_read_u16((uint32_t) 1073820676U);
        
        /* reg modify spi4->cr2: setBit spi_cr2_txeie */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073820676U, (uint16_t) (n_r4 | (uint16_t) ((uint16_t) 1U << (uint16_t) 7U)));
    }
}

void emitter_periodic_chan_1(const struct spi_transaction_request *n_var0)
{
    emitter_periodic_chan_1_thread_period_250ms_emit(n_var0);
}
