/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __CALLBACK_DMA1_STREAM6_IRQHANDLER_H__
#define __CALLBACK_DMA1_STREAM6_IRQHANDLER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <smaccm_thread_signal_DMA1_Stream6_IRQHandler.h>
void callback_DMA1_Stream6_IRQHandler(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __CALLBACK_DMA1_STREAM6_IRQHANDLER_H__ */
