/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __DMA1_STREAM5_IRQHANDLER_H__
#define __DMA1_STREAM5_IRQHANDLER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "blinker_monitor.h"
#include "led_monitor.h"
#include "uart2_dma_rx_byte_shim_monitor.h"
#include "dma_monitor.h"
#include "echoprompt_monitor.h"
#include "settableLED_monitor.h"
#include "callback_DMA1_Stream5_IRQHandler.h"
#include "callback_DMA1_Stream6_IRQHandler.h"
#include "callback_11ms.h"
#include "callback_50ms.h"
#include "callback_333ms.h"
#include "callback_systemInit.h"
void DMA1_Stream5_IRQHandler(void);

#ifdef __cplusplus
}
#endif
#endif /* __DMA1_STREAM5_IRQHANDLER_H__ */
