/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __DMA_MONITOR_H__
#define __DMA_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_dma.h>
#include <ivory_hw_prim.h>
#include <ref_to_uint32.h>
extern struct ivory_string_UARTBuffer uart2_dma_req_buf;
extern bool uart2_dma_tx_active;
extern uint32_t uart2_dma_tx_complete;
extern uint32_t uart2_dma_tx_transfer_err;
extern uint32_t uart2_dma_tx_direct_err;
extern struct ivory_string_UARTBuffer uart2_dma_rx0_buf;
extern struct ivory_string_UARTBuffer uart2_dma_rx1_buf;
extern struct ivory_string_UARTBuffer uart2_dma_isr_buf;
extern uint32_t uart2_dma_rx_complete;
extern uint32_t uart2_dma_rx_transfer_err;
extern uint32_t uart2_dma_rx_direct_err;
void callback_dmauart_hw_init(const int64_t *n_var0);
void callback_dmauart_tx_init(const int64_t *n_var0);
void callback_req_chan(const struct ivory_string_UARTBuffer *n_var0);
void callback_tx_stream_interrupt(const int64_t *n_var0);
void callback_dmauart_rx_init(const int64_t *n_var0);
void callback_rx_stream_interrupt(const int64_t *n_var0);
void callback_rx_flush(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __DMA_MONITOR_H__ */
