/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __ECHOPROMPT_MONITOR_H__
#define __ECHOPROMPT_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_echoprompt.h>
extern struct ivory_string_UARTBuffer out_req;
extern bool flush_defer;
extern bool initialized;
void callback_flush(const int64_t *n_var0);
void callback_ostream(const uint8_t *n_var0);
void callback_result(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __ECHOPROMPT_MONITOR_H__ */
