/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __UART2_DMA_RX_BYTE_SHIM_MONITOR_H__
#define __UART2_DMA_RX_BYTE_SHIM_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_uart2_dma_rx_byte_shim.h>
void callback_uart2_buf_rx(const struct ivory_string_UARTBuffer *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __UART2_DMA_RX_BYTE_SHIM_MONITOR_H__ */
