/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __CAN1_TX_IRQHANDLER_H__
#define __CAN1_TX_IRQHANDLER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "can1PeripheralDriver_monitor.h"
#include "simplecontroller_monitor.h"
#include "callback_CAN1_RX0_IRQHandler.h"
#include "callback_CAN1_RX1_IRQHandler.h"
#include "callback_CAN1_TX_IRQHandler.h"
#include "callback_250ms.h"
#include "callback_systemInit.h"
void CAN1_TX_IRQHandler(void);

#ifdef __cplusplus
}
#endif
#endif /* __CAN1_TX_IRQHANDLER_H__ */
