/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __CAN1PERIPHERALDRIVER_MONITOR_H__
#define __CAN1PERIPHERALDRIVER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "canDriverTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_can1PeripheralDriver.h>
#include <ivory_hw_prim.h>
void callback_init(const int64_t *n_var0);
void callback_request(const struct can_message *n_var0);
void callback_abort(const bool *n_var0);
void callback_request_2(const struct can_message *n_var0);
void callback_abort_2(const bool *n_var0);
void callback_request_3(const struct can_message *n_var0);
void callback_abort_3(const bool *n_var0);
void callback_tx_irq(const int64_t *n_var0);
void callback_rx0_irq(const int64_t *n_var0);
void callback_rx1_irq(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __CAN1PERIPHERALDRIVER_MONITOR_H__ */
