/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __SIMPLECONTROLLER_MONITOR_H__
#define __SIMPLECONTROLLER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "canDriverTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_simplecontroller.h>
extern bool tx_pending;
extern struct can_message last_sent;
extern uint32_t can_received_count;
void callback_init_2(const int64_t *n_var0);
void callback_periodic(const int64_t *n_var0);
void callback_tx_complete(const bool *n_var0);
void callback_result(const struct can_message *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __SIMPLECONTROLLER_MONITOR_H__ */
