/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_TIME_H__
#define __TOWER_TIME_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <clock_driver.h>
int64_t tower_get_time(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_TIME_H__ */
