/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_init.h"

static void handler_run_hardwareinit_thread_init(const int64_t *n_var0);

static void handler_run_init_thread_init(const int64_t *n_var0);

void loop_thread_init(void)
{
    int64_t n_local0 = (int64_t) 0;
    int64_t *n_ref1 = &n_local0;
    
    ASSERTS((bool) ((uint8_t) 12U < (uint8_t) ((uint8_t) 1U << (uint8_t) 4U)));
    ivory_hw_io_write_u8((uint32_t) 3758154790U, (uint8_t) ((uint8_t) 12U << (uint8_t) 4U));
    handler_run_init_thread_init(n_ref1);
    handler_run_hardwareinit_thread_init(n_ref1);
    return;
}

void handler_run_hardwareinit_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_settableLED();
    /* run callbacks */
    callback_hardwareinit_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_settableLED();
    /* deliver emitters */
    ;
}

void handler_run_init_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_dma();
    /* run callbacks */
    callback_init_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_dma();
    /* deliver emitters */
    ;
}
