/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_init.h"

void callback_hardwareinit_thread_init(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_r0 | (uint32_t) ((uint32_t) 1U << (uint32_t) 4U)));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) (n_r1 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 12U)) | (uint32_t) (0 << (uint32_t) 12U)));
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_12 */
    ;
    
    uint32_t n_cse12 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U);
    uint32_t n_cse14 = (uint32_t) (0 << (uint32_t) 24U);
    
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) ((uint32_t) (n_r2 & n_cse12) | n_cse14));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073877004U);
    
    /* reg modify gpioE->pupd: setField gpio_pupd_12 */
    ivory_hw_io_write_u32((uint32_t) 1073877004U, (uint32_t) (n_cse14 | (uint32_t) (n_cse12 & n_r3)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_cse12 & n_r4) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
}

void callback_init_thread_init(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887296U);
    
    /* reg modify rcc_apb1enr: setBit rcc_apb1en_uart2 */
    ivory_hw_io_write_u32((uint32_t) 1073887296U, (uint32_t) (n_r0 | (uint32_t) ((uint32_t) 1U << (uint32_t) 17U)));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpiod */
    ;
    
    uint32_t n_cse4 = (uint32_t) ((uint32_t) 1U << (uint32_t) 3U);
    
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_r1 | n_cse4));
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073875976U);
    
    /* reg modify gpioD->ospeed: setField gpio_ospeed_5 */
    ;
    
    uint32_t n_cse8 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 10U);
    uint32_t n_cse12 = (uint32_t) (uint8_t) ((uint8_t) 2U << 0);
    uint32_t n_cse13 = (uint32_t) (n_cse12 << (uint32_t) 10U);
    
    ivory_hw_io_write_u32((uint32_t) 1073875976U, (uint32_t) ((uint32_t) (n_r2 & n_cse8) | n_cse13));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073875972U);
    
    /* reg modify gpioD->otype: setField gpio_otype_5 */
    ivory_hw_io_write_u32((uint32_t) 1073875972U, (uint32_t) ((uint32_t) (n_r3 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 5U)) | (uint32_t) (0 << (uint32_t) 5U)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073875980U);
    
    /* reg modify gpioD->pupd: setField gpio_pupd_5 */
    ;
    
    uint32_t n_cse26 = (uint32_t) (uint8_t) ((uint8_t) 1U << 0);
    
    ivory_hw_io_write_u32((uint32_t) 1073875980U, (uint32_t) ((uint32_t) (n_cse8 & n_r4) | (uint32_t) (n_cse26 << (uint32_t) 10U)));
    
    uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073876000U);
    
    /* reg modify gpioD->afrl: setField gpio_afrl_5 */
    ;
    
    uint32_t n_cse35 = (uint32_t) (uint8_t) ((uint8_t) 7U << 0);
    
    ivory_hw_io_write_u32((uint32_t) 1073876000U, (uint32_t) ((uint32_t) (n_r5 & (uint32_t) ~(uint32_t) ((uint32_t) 15U << (uint32_t) 20U)) | (uint32_t) (n_cse35 << (uint32_t) 20U)));
    
    uint32_t n_r6 = ivory_hw_io_read_u32((uint32_t) 1073875968U);
    
    /* reg modify gpioD->mode: setField gpio_mode_5 */
    ivory_hw_io_write_u32((uint32_t) 1073875968U, (uint32_t) (n_cse13 | (uint32_t) (n_cse8 & n_r6)));
    
    uint32_t n_r7 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpiod */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse4 | n_r7));
    
    uint32_t n_r8 = ivory_hw_io_read_u32((uint32_t) 1073875976U);
    
    /* reg modify gpioD->ospeed: setField gpio_ospeed_6 */
    ;
    
    uint32_t n_cse45 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 12U);
    uint32_t n_cse47 = (uint32_t) (n_cse12 << (uint32_t) 12U);
    
    ivory_hw_io_write_u32((uint32_t) 1073875976U, (uint32_t) ((uint32_t) (n_r8 & n_cse45) | n_cse47));
    
    uint32_t n_r9 = ivory_hw_io_read_u32((uint32_t) 1073875972U);
    
    /* reg modify gpioD->otype: setField gpio_otype_6 */
    ;
    
    uint32_t n_cse50 = (uint32_t) ((uint32_t) 1U << (uint32_t) 6U);
    
    ivory_hw_io_write_u32((uint32_t) 1073875972U, (uint32_t) ((uint32_t) (n_r9 & (uint32_t) ~n_cse50) | (uint32_t) (0 << (uint32_t) 6U)));
    
    uint32_t n_r10 = ivory_hw_io_read_u32((uint32_t) 1073875980U);
    
    /* reg modify gpioD->pupd: setField gpio_pupd_6 */
    ivory_hw_io_write_u32((uint32_t) 1073875980U, (uint32_t) ((uint32_t) (n_cse45 & n_r10) | (uint32_t) (n_cse26 << (uint32_t) 12U)));
    
    uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073876000U);
    
    /* reg modify gpioD->afrl: setField gpio_afrl_6 */
    ivory_hw_io_write_u32((uint32_t) 1073876000U, (uint32_t) ((uint32_t) (n_r11 & (uint32_t) ~(uint32_t) ((uint32_t) 15U << (uint32_t) 24U)) | (uint32_t) (n_cse35 << (uint32_t) 24U)));
    
    uint32_t n_r12 = ivory_hw_io_read_u32((uint32_t) 1073875968U);
    
    /* reg modify gpioD->mode: setField gpio_mode_6 */
    ivory_hw_io_write_u32((uint32_t) 1073875968U, (uint32_t) (n_cse47 | (uint32_t) (n_cse45 & n_r12)));
    /* reg get uart2->cr1:  */
    ;
    
    uint16_t n_r14 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
    bool n_let15 = (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r14 >> (uint16_t) 15U) & (uint16_t) 1U));
    uint32_t n_cse77 = (uint32_t) ((uint32_t) 115200U * (uint32_t) (n_let15 ? (uint32_t) 2U : (uint32_t) 4U));
    uint32_t n_cse81 = (uint32_t) ((uint32_t) 1050000000U / n_cse77);
    uint32_t n_cse89 = (uint32_t) (n_cse81 / (uint32_t) 100U);
    uint32_t n_let17 = (uint32_t) (n_cse89 << (uint32_t) 4U);
    uint32_t n_let18 = (uint32_t) (n_cse81 - (uint32_t) ((uint32_t) 100U * (uint32_t) (n_let17 >> (uint32_t) 4U)));
    uint32_t n_cse99 = (uint32_t) ((uint32_t) (n_let18 * (uint32_t) 8U) + (uint32_t) 50U);
    uint32_t n_cse102 = (uint32_t) (n_cse99 / (uint32_t) 100U);
    uint32_t n_cse109 = (uint32_t) ((uint32_t) 50U + (uint32_t) (n_let18 * (uint32_t) 16U));
    uint32_t n_cse112 = (uint32_t) (n_cse109 / (uint32_t) 100U);
    uint32_t n_let19 = (uint32_t) (n_let17 | (uint32_t) (n_let15 ? (uint32_t) (n_cse102 & (uint32_t) 7U) : (uint32_t) (n_cse112 & (uint32_t) 15U)));
    
    /* reg set uart2->brr: setField uart_brr_div */
    ivory_hw_io_write_u16((uint32_t) 1073759240U, (uint16_t) ((uint16_t) (uint32_t) (n_let19 & (uint32_t) 65535U) << 0));
    
    uint16_t n_r20 = ivory_hw_io_read_u16((uint32_t) 1073759248U);
    
    /* reg modify uart2->cr2: setField uart_cr2_stop */
    ;
    
    uint16_t n_cse134 = (uint16_t) (0 << (uint16_t) 12U);
    
    ivory_hw_io_write_u16((uint32_t) 1073759248U, (uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 3U << (uint16_t) 12U) & n_r20) | n_cse134));
    
    uint16_t n_r21 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
    
    /* reg modify uart2->cr1: setField uart_cr1_m */
    ivory_hw_io_write_u16((uint32_t) 1073759244U, (uint16_t) (n_cse134 | (uint16_t) (n_r21 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U))));
    
    uint16_t n_r22 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
    
    /* reg modify uart2->cr1: setField uart_cr1_pce */
    ivory_hw_io_write_u16((uint32_t) 1073759244U, (uint16_t) ((uint16_t) (n_r22 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) | (uint16_t) ((uint16_t) 0 << (uint16_t) 10U)));
    /* reg set nvic_iser1: setBit nvic_iser_setena.[6] */
    ivory_hw_io_write_u32((uint32_t) 3758153988U, n_cse50);
    
    uint16_t n_r23 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
    
    /* reg modify uart2->cr1: setBit uart_cr1_txeie, setBit uart_cr1_rxneie, setBit uart_cr1_te, setBit uart_cr1_re */
    ivory_hw_io_write_u16((uint32_t) 1073759244U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 3U) | (uint16_t) ((uint16_t) 1U << (uint16_t) 5U)) | n_r23) | (uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 2U)));
    
    uint16_t n_r24 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
    
    /* reg modify uart2->cr1: setBit uart_cr1_ue */
    ivory_hw_io_write_u16((uint32_t) 1073759244U, (uint16_t) (n_r24 | (uint16_t) ((uint16_t) 1U << (uint16_t) 13U)));
}
