/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_echoprompt.h"

struct mutex lock_echoprompt;

void monitor_init_echoprompt(void)
{
    ivory_freertos_mutex_create(&lock_echoprompt);
}

void monitor_lock_echoprompt(void)
{
    ivory_freertos_mutex_takeblocking(&lock_echoprompt);
}

void monitor_unlock_echoprompt(void)
{
    ivory_freertos_mutex_give(&lock_echoprompt);
}
