/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_1ms.h"

static void emitter_init_2_chan_5(const uint8_t *n_var0);

void callback_init_2_thread_period_1ms(const int64_t *n_var0)
{
    bool n_deref0 = initialized;
    
    if ((bool) !n_deref0) {
        initialized = true;
        
        uint8_t n_local1 = (uint8_t) 104U;
        uint8_t *n_ref2 = &n_local1;
        
        emitter_init_2_chan_5(n_ref2);
        
        uint8_t n_local3 = (uint8_t) 101U;
        uint8_t *n_ref4 = &n_local3;
        
        emitter_init_2_chan_5(n_ref4);
        
        uint8_t n_local5 = (uint8_t) 108U;
        uint8_t *n_ref6 = &n_local5;
        
        emitter_init_2_chan_5(n_ref6);
        
        uint8_t n_local7 = (uint8_t) 108U;
        uint8_t *n_ref8 = &n_local7;
        
        emitter_init_2_chan_5(n_ref8);
        
        uint8_t n_local9 = (uint8_t) 111U;
        uint8_t *n_ref10 = &n_local9;
        
        emitter_init_2_chan_5(n_ref10);
        
        uint8_t n_local11 = (uint8_t) 32U;
        uint8_t *n_ref12 = &n_local11;
        
        emitter_init_2_chan_5(n_ref12);
        
        uint8_t n_local13 = (uint8_t) 119U;
        uint8_t *n_ref14 = &n_local13;
        
        emitter_init_2_chan_5(n_ref14);
        
        uint8_t n_local15 = (uint8_t) 111U;
        uint8_t *n_ref16 = &n_local15;
        
        emitter_init_2_chan_5(n_ref16);
        
        uint8_t n_local17 = (uint8_t) 114U;
        uint8_t *n_ref18 = &n_local17;
        
        emitter_init_2_chan_5(n_ref18);
        
        uint8_t n_local19 = (uint8_t) 108U;
        uint8_t *n_ref20 = &n_local19;
        
        emitter_init_2_chan_5(n_ref20);
        
        uint8_t n_local21 = (uint8_t) 100U;
        uint8_t *n_ref22 = &n_local21;
        
        emitter_init_2_chan_5(n_ref22);
        
        uint8_t n_local23 = (uint8_t) 10U;
        uint8_t *n_ref24 = &n_local23;
        
        emitter_init_2_chan_5(n_ref24);
        
        uint8_t n_local25 = (uint8_t) 116U;
        uint8_t *n_ref26 = &n_local25;
        
        emitter_init_2_chan_5(n_ref26);
        
        uint8_t n_local27 = (uint8_t) 111U;
        uint8_t *n_ref28 = &n_local27;
        
        emitter_init_2_chan_5(n_ref28);
        
        uint8_t n_local29 = (uint8_t) 119U;
        uint8_t *n_ref30 = &n_local29;
        
        emitter_init_2_chan_5(n_ref30);
        
        uint8_t n_local31 = (uint8_t) 101U;
        uint8_t *n_ref32 = &n_local31;
        
        emitter_init_2_chan_5(n_ref32);
        
        uint8_t n_local33 = (uint8_t) 114U;
        uint8_t *n_ref34 = &n_local33;
        
        emitter_init_2_chan_5(n_ref34);
        
        uint8_t n_local35 = (uint8_t) 62U;
        uint8_t *n_ref36 = &n_local35;
        
        emitter_init_2_chan_5(n_ref36);
        
        uint8_t n_local37 = (uint8_t) 32U;
        uint8_t *n_ref38 = &n_local37;
        
        emitter_init_2_chan_5(n_ref38);
    }
}

void callback_uart_byte_tosend_thread_period_1ms(const uint8_t *n_var0)
{
    uint8_t n_deref0 = *n_var0;
    int32_t n_deref1 = buffer.ivory_string_UARTBuffer_len;
    
    if ((bool) (n_deref1 < (int32_t) 128)) {
        buffer.ivory_string_UARTBuffer_data[n_deref1 % 128] = n_deref0;
        buffer.ivory_string_UARTBuffer_len = (int32_t) (n_deref1 + (int32_t) 1);
    }
}

void emitter_init_2_chan_5(const uint8_t *n_var0)
{
    emitter_init_2_chan_5_thread_period_1ms_emit(n_var0);
}
