/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_UART_UNBUFFER_H__
#define __TOWER_STATE_MONITOR_UART_UNBUFFER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
extern bool flush_defer;
extern struct ivory_string_UARTBuffer buffer;

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_UART_UNBUFFER_H__ */
