/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_THREAD_PERIOD_1MS_H__
#define __TOWER_GEN_THREAD_PERIOD_1MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include "tower_user_thread_period_1ms.h"
#include "tower_gen_monitor_echoprompt.h"
#include "tower_gen_monitor_uart_unbuffer.h"
#include <freertos_task_wrapper.h>
#include <freertos_time_wrapper.h>
void loop_thread_period_1ms(struct taskarg *n_var0);
void emitter_init_2_chan_5_thread_period_1ms_emit(const uint8_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_THREAD_PERIOD_1MS_H__ */
