/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_SETTABLELED_H__
#define __TOWER_STATE_MONITOR_SETTABLELED_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include <ivory_hw_prim.h>

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_SETTABLELED_H__ */
