/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_init.h"

void tower_entry(void)
{
    monitor_init_dma();
    monitor_init_uart_unbuffer();
    monitor_init_echoprompt();
    monitor_init_settableLED();
    ivory_freertos_binary_semaphore_create(&signal_semaphore_thread_signal_USART2_IRQHandler);
    loop_thread_init();
    ivory_freertos_task_create(loop_thread_signal_USART2_IRQHandler, (uint32_t) 2560U, (uint8_t) 4U, "thread_signal_USART2_IRQHandler");
    ivory_freertos_task_create(loop_thread_period_1ms, (uint32_t) 2560U, (uint8_t) 3U, "thread_period_1ms");
    ivory_freertos_task_create(loop_thread_period_10ms, (uint32_t) 2560U, (uint8_t) 2U, "thread_period_10ms");
}
