/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_DMA_H__
#define __TOWER_STATE_MONITOR_DMA_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include <ivory_hw_prim.h>
extern uint32_t uart2_rx_overruns;
extern uint32_t uart2_rx_success;
extern struct ivory_string_UARTBuffer req_buf;
extern int32_t req_pos;

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_DMA_H__ */
