/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_MONITOR_SETTABLELED_H__
#define __TOWER_GEN_MONITOR_SETTABLELED_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include <freertos_mutex_wrapper.h>
extern struct mutex lock_settableLED;
void monitor_init_settableLED(void);
void monitor_lock_settableLED(void);
void monitor_unlock_settableLED(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_MONITOR_SETTABLELED_H__ */
