resolver: lts-11.22
packages:
- '.'
- location: /home/x2/FlyCube/smaccmpilot-build/smaccmpilot-stm32f4/src/smaccm-comm-schema/../../../ivory
  extra-dep: true
  subdirs:
    - ivory
    - ivory-artifact
    - ivory-backend-c
    - ivory-hw
    - ivory-opts
    - ivory-serialize
    - ivory-stdlib
- location: /home/x2/FlyCube/smaccmpilot-build/smaccmpilot-stm32f4/src/smaccm-comm-schema/../../../tower
  extra-dep: true
  subdirs:
    - tower
    - tower-config
    - tower-hal
- location: /home/x2/FlyCube/smaccmpilot-build/smaccmpilot-stm32f4/src/smaccm-comm-schema/../../../ivory-tower-stm32
  extra-dep: true
  subdirs:
    - ivory-bsp-stm32
    - ivory-freertos-bindings
    - tower-freertos-stm32
extra-deps:
  - exception-mtl-0.4
  - ghc-srcspan-plugin-0.2.1.0
  - language-c-quote-0.11.6
  - mainland-pretty-0.4.1.4
  - symbol-0.2.4
  - th-abstraction-0.2.5.0
install-ghc: true