# This makefile is autogenerated. DO NOT EDIT.

include AADL_FILES.mk

RAMSES_PATH ?= 

SMACCM_PATH ?= ./

export RAMSES_DIR=$(RAMSES_PATH)/ramses_resource

export AADL2RTOS_CONFIG_DIR=$(RAMSES_PATH)/aadl2rtos_resource

.PHONY: all tower-clean


.tag.ramses: 
	java -jar $(RAMSES_PATH)/ramses.jar -g rtos -i $(AADL2RTOS_CONFIG_DIR) -o . -l trace -s sys.impl -m SMACCM_SYS.aadl,$(AADL_LIST)
	touch .tag.ramses


tower-clean: 
	-rm -rf .tag.ramses


