/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_rngPeripheral.h"

struct mutex lock_rngPeripheral;

void monitor_init_rngPeripheral(void)
{
    ivory_freertos_mutex_create(&lock_rngPeripheral);
}

void monitor_lock_rngPeripheral(void)
{
    ivory_freertos_mutex_takeblocking(&lock_rngPeripheral);
}

void monitor_unlock_rngPeripheral(void)
{
    ivory_freertos_mutex_give(&lock_rngPeripheral);
}
