/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_INIT_H__
#define __TOWER_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_gen_monitor_rngPeripheral.h"
#include "tower_gen_monitor_i2c_fuzzer.h"
#include "tower_gen_thread_period_1ms.h"
#include "tower_gen_thread_period_90ms.h"
#include "tower_gen_thread_init.h"
#include <freertos_task_wrapper.h>
void tower_entry(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_INIT_H__ */
