/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_THREAD_INIT_H__
#define __TOWER_GEN_THREAD_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_user_thread_init.h"
#include "tower_gen_monitor_rngPeripheral.h"
#include "tower_gen_monitor_i2c_fuzzer.h"
#include <freertos_time_wrapper.h>
void loop_thread_init(void);
void emitter_use_rng_init_chan_2_thread_init_emit(const bool *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_THREAD_INIT_H__ */
