/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_90ms.h"

void callback_chaos_thread_period_90ms(const int64_t *n_var0)
{
    int64_t n_deref0 = next_run;
    int64_t n_r1 = tower_get_time();
    
    if ((bool) !(bool) ((bool) (n_r1 > n_deref0) || (bool) ((int64_t) 0 == n_deref0))) {
        uint32_t n_deref2 = sda_pattern;
        uint32_t n_deref3 = scl_pattern;
        
        for (int32_t n_ix4 = (int32_t) 0; n_ix4 <= (int32_t) 31; n_ix4++) {
            uint32_t n_cse13 = (uint32_t) ((bool) (n_ix4 > (int32_t) 0) ? (uint32_t) n_ix4 : 0);
            
            if ((bool) ((uint32_t) 1U == (uint32_t) ((uint32_t) (n_deref2 >> n_cse13) & (uint32_t) 1U))) {
                uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                
                uint32_t n_cse18 = (uint32_t) ((uint32_t) 1U << (uint32_t) 8U);
                
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_r5 | n_cse18));
                
                uint32_t n_r6 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r6));
                
                uint32_t n_r7 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r7));
                
                uint32_t n_r8 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r8));
                
                uint32_t n_r9 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r9));
                
                uint32_t n_r10 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r10));
                
                uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r11));
                
                uint32_t n_r12 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r12));
                
                uint32_t n_r13 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r13));
                
                uint32_t n_r14 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r14));
                
                uint32_t n_r15 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r15));
                
                uint32_t n_r16 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r16));
                
                uint32_t n_r17 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r17));
                
                uint32_t n_r18 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r18));
                
                uint32_t n_r19 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r19));
                
                uint32_t n_r20 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse18 | n_r20));
            } else {
                uint32_t n_r21 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                
                uint32_t n_cse51 = (uint32_t) ((uint32_t) 1U << (uint32_t) 24U);
                
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_r21 | n_cse51));
                
                uint32_t n_r22 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r22));
                
                uint32_t n_r23 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r23));
                
                uint32_t n_r24 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r24));
                
                uint32_t n_r25 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r25));
                
                uint32_t n_r26 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r26));
                
                uint32_t n_r27 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r27));
                
                uint32_t n_r28 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r28));
                
                uint32_t n_r29 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r29));
                
                uint32_t n_r30 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r30));
                
                uint32_t n_r31 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r31));
                
                uint32_t n_r32 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r32));
                
                uint32_t n_r33 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r33));
                
                uint32_t n_r34 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r34));
                
                uint32_t n_r35 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r35));
                
                uint32_t n_r36 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_8 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse51 | n_r36));
            }
            if ((bool) ((uint32_t) 1U == (uint32_t) ((uint32_t) (n_deref3 >> n_cse13) & (uint32_t) 1U))) {
                uint32_t n_r37 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                
                uint32_t n_cse87 = (uint32_t) ((uint32_t) 1U << (uint32_t) 9U);
                
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_r37 | n_cse87));
                
                uint32_t n_r38 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r38));
                
                uint32_t n_r39 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r39));
                
                uint32_t n_r40 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r40));
                
                uint32_t n_r41 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r41));
                
                uint32_t n_r42 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r42));
                
                uint32_t n_r43 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r43));
                
                uint32_t n_r44 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r44));
                
                uint32_t n_r45 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r45));
                
                uint32_t n_r46 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r46));
                
                uint32_t n_r47 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r47));
                
                uint32_t n_r48 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r48));
                
                uint32_t n_r49 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r49));
                
                uint32_t n_r50 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r50));
                
                uint32_t n_r51 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r51));
                
                uint32_t n_r52 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_bs_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse87 | n_r52));
            } else {
                uint32_t n_r53 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                
                uint32_t n_cse120 = (uint32_t) ((uint32_t) 1U << (uint32_t) 25U);
                
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_r53 | n_cse120));
                
                uint32_t n_r54 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r54));
                
                uint32_t n_r55 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r55));
                
                uint32_t n_r56 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r56));
                
                uint32_t n_r57 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r57));
                
                uint32_t n_r58 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r58));
                
                uint32_t n_r59 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r59));
                
                uint32_t n_r60 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r60));
                
                uint32_t n_r61 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r61));
                
                uint32_t n_r62 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r62));
                
                uint32_t n_r63 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r63));
                
                uint32_t n_r64 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r64));
                
                uint32_t n_r65 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r65));
                
                uint32_t n_r66 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r66));
                
                uint32_t n_r67 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r67));
                
                uint32_t n_r68 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
                
                /* reg modify gpioB->bsrr: setBit gpio_br_9 */
                ;
                ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) (n_cse120 | n_r68));
            }
        }
        
        uint32_t n_r69 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
        
        /* reg modify gpioB->bsrr: setBit gpio_br_8 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) ((uint32_t) ((uint32_t) 1U << (uint32_t) 24U) | n_r69));
        
        uint32_t n_r70 = ivory_hw_io_read_u32((uint32_t) 1073873944U);
        
        /* reg modify gpioB->bsrr: setBit gpio_br_9 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073873944U, (uint32_t) ((uint32_t) ((uint32_t) 1U << (uint32_t) 25U) | n_r70));
        
        int64_t n_deref71 = next_delay;
        int64_t n_r72 = tower_get_time();
        
        next_run = (int64_t) (n_r72 + n_deref71);
    }
}
