/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_i2c_fuzzer.h"

struct mutex lock_i2c_fuzzer;

void monitor_init_i2c_fuzzer(void)
{
    ivory_freertos_mutex_create(&lock_i2c_fuzzer);
}

void monitor_lock_i2c_fuzzer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_i2c_fuzzer);
}

void monitor_unlock_i2c_fuzzer(void)
{
    ivory_freertos_mutex_give(&lock_i2c_fuzzer);
}
