/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_MONITOR_I2C_FUZZER_H__
#define __TOWER_GEN_MONITOR_I2C_FUZZER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <freertos_mutex_wrapper.h>
extern struct mutex lock_i2c_fuzzer;
void monitor_init_i2c_fuzzer(void);
void monitor_lock_i2c_fuzzer(void);
void monitor_unlock_i2c_fuzzer(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_MONITOR_I2C_FUZZER_H__ */
