/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_init.h"

static bool emitter_use_rng_init_chan_2_thread_init_message_0;

static uint32_t emitter_use_rng_init_chan_2_thread_init_message_count;

static void handler_run_use_rng_init_thread_init(const int64_t *n_var0);

static void handler_run_use_rng_thread_init(const bool *n_var0);

static void handler_run_init_thread_init(const int64_t *n_var0);

static void handler_run_rngInit_thread_init(const int64_t *n_var0);

void loop_thread_init(void)
{
    int64_t n_local0 = (int64_t) 0;
    int64_t *n_ref1 = &n_local0;
    
    handler_run_rngInit_thread_init(n_ref1);
    handler_run_init_thread_init(n_ref1);
    handler_run_use_rng_init_thread_init(n_ref1);
    return;
}

void emitter_use_rng_init_chan_2_thread_init_emit(const bool *n_var0)
{
    uint32_t n_deref0 = emitter_use_rng_init_chan_2_thread_init_message_count;
    
    if ((bool) (n_deref0 <= 0)) {
        emitter_use_rng_init_chan_2_thread_init_message_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
        emitter_use_rng_init_chan_2_thread_init_message_0 = *n_var0;
    }
}

void handler_run_use_rng_init_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    emitter_use_rng_init_chan_2_thread_init_message_count = (uint32_t) 0U;
    /* take monitor lock */
    monitor_lock_i2c_fuzzer();
    /* run callbacks */
    callback_use_rng_init_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c_fuzzer();
    /* deliver emitters */
    ;
    
    uint32_t n_deref0 = emitter_use_rng_init_chan_2_thread_init_message_count;
    
    if ((bool) (0 < n_deref0)) {
        handler_run_use_rng_thread_init(&emitter_use_rng_init_chan_2_thread_init_message_0);
    }
}

void handler_run_use_rng_thread_init(const bool *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_i2c_fuzzer();
    /* run callbacks */
    callback_use_rng_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c_fuzzer();
    /* deliver emitters */
    ;
}

void handler_run_init_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_i2c_fuzzer();
    /* run callbacks */
    callback_init_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c_fuzzer();
    /* deliver emitters */
    ;
}

void handler_run_rngInit_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_rngPeripheral();
    /* run callbacks */
    callback_rngInit_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_rngPeripheral();
    /* deliver emitters */
    ;
}
