/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_USER_THREAD_PERIOD_1MS_H__
#define __TOWER_USER_THREAD_PERIOD_1MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_state_monitor_rngPeripheral.h"
#include "tower_state_monitor_i2c_fuzzer.h"
#include "tower_gen_thread_period_1ms.h"
#include "tower_time.h"
void callback_use_rng_raw_thread_period_1ms(const uint32_t *n_var0);
void callback_use_rng_thread_period_1ms(const bool *n_var0);
void callback_rngPoll_thread_period_1ms(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_USER_THREAD_PERIOD_1MS_H__ */
