/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_1ms.h"

static void emitter_use_rng_raw_chan_2(const bool *n_var0);

static void emitter_rngPoll_chan_1(const uint32_t *n_var0);

void callback_use_rng_raw_thread_period_1ms(const uint32_t *n_var0)
{
    last_value = *n_var0;
    
    bool n_local0 = false;
    bool *n_ref1 = &n_local0;
    
    emitter_use_rng_raw_chan_2(n_ref1);
}

void callback_use_rng_thread_period_1ms(const bool *n_var0)
{
    bool n_deref0 = *n_var0;
    
    if (n_deref0) {
        use_rng_cont.state = (uint32_t) 7U;
    }
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            uint32_t n_state = use_rng_cont.state;
            
            if ((bool) (n_state == (uint32_t) 1U)) {
                use_rng_cont.r12 = last_value;
                use_rng_cont.deref13 = use_rng_cont.r12;
                
                uint32_t n_cont7 = use_rng_cont.deref13;
                
                scl_pattern = n_cont7;
                use_rng_cont.state = (uint32_t) 3U;
                break;
            }
            if ((bool) ((uint32_t) 2U == n_state)) {
                use_rng_cont.r10 = last_value;
                use_rng_cont.deref11 = use_rng_cont.r10;
                
                uint32_t n_cont6 = use_rng_cont.deref11;
                
                sda_pattern = n_cont6;
                use_rng_cont.state = (uint32_t) 1U;
                break;
            }
            if ((bool) (n_state == (uint32_t) 3U)) {
                use_rng_cont.r8 = last_value;
                use_rng_cont.deref9 = use_rng_cont.r8;
                
                uint32_t n_cont5 = use_rng_cont.deref9;
                uint32_t n_cse22 = (uint32_t) (n_cont5 / (uint32_t) 1000U);
                
                next_delay = (int64_t) (uint32_t) (n_cse22 + (uint32_t) 5000U);
                use_rng_cont.state = (uint32_t) 2U;
                break;
            }
            if ((bool) (n_state == (uint32_t) 4U)) {
                use_rng_cont.r4 = last_value;
                use_rng_cont.deref5 = use_rng_cont.r4;
                
                uint32_t n_cont2 = use_rng_cont.deref5;
                
                scl_pattern = n_cont2;
                use_rng_cont.deref6 = next_delay;
                
                int64_t n_r7 = tower_get_time();
                
                use_rng_cont.r7 = n_r7;
                
                int64_t n_cont3 = use_rng_cont.r7;
                int64_t n_cont4 = use_rng_cont.deref6;
                
                next_run = (int64_t) (n_cont3 + n_cont4);
                use_rng_cont.state = (uint32_t) 3U;
                break;
            }
            if ((bool) (n_state == (uint32_t) 5U)) {
                use_rng_cont.r2 = last_value;
                use_rng_cont.deref3 = use_rng_cont.r2;
                
                uint32_t n_cont1 = use_rng_cont.deref3;
                
                sda_pattern = n_cont1;
                use_rng_cont.state = (uint32_t) 4U;
                break;
            }
            if ((bool) (n_state == (uint32_t) 6U)) {
                use_rng_cont.r0 = last_value;
                use_rng_cont.deref1 = use_rng_cont.r0;
                
                uint32_t n_cont0 = use_rng_cont.deref1;
                uint32_t n_cse55 = (uint32_t) (n_cont0 / (uint32_t) 1000U);
                
                next_delay = (int64_t) (uint32_t) ((uint32_t) 5000U + n_cse55);
                use_rng_cont.state = (uint32_t) 5U;
                break;
            }
            if ((bool) ((uint32_t) 7U == n_state)) {
                use_rng_cont.state = (uint32_t) 6U;
                break;
            }
        }
    }
}

void callback_rngPoll_thread_period_1ms(const int64_t *n_var0)
{
    /* reg get rng->sr:  */
    ;
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1342572548U);
    
    if ((bool) ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> 0) & (uint32_t) 1U) & (uint16_t) 255U)) && (bool) ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 2U) & (uint32_t) 1U) & (uint16_t) 255U)) && (bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 1U) & (uint32_t) 1U) &
                                                                                                                                                                                                                                                                                                                         (uint16_t) 255U))))) {
        /* reg get rng->dr:  */
        ;
        
        uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1342572552U);
        uint32_t n_let2 = (uint32_t) (n_r1 >> 0);
        uint32_t n_local3 = n_let2;
        uint32_t *n_ref4 = &n_local3;
        
        emitter_rngPoll_chan_1(n_ref4);
    }
}

void emitter_use_rng_raw_chan_2(const bool *n_var0)
{
    emitter_use_rng_raw_chan_2_thread_period_1ms_emit(n_var0);
}

void emitter_rngPoll_chan_1(const uint32_t *n_var0)
{
    emitter_rngPoll_chan_1_thread_period_1ms_emit(n_var0);
}
