/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_period_90ms.h"

static void handler_run_chaos_thread_period_90ms(const int64_t *n_var0);

void loop_thread_period_90ms(struct taskarg *n_var0)
{
    uint32_t n_r0 = ivory_freertos_time_gettickrate_ms();
    uint32_t n_r1 = ivory_freertos_time_gettickcount();
    uint32_t n_local2 = n_r1;
    uint32_t *n_ref3 = &n_local2;
    
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            ivory_freertos_time_delayuntil(n_ref3, (uint32_t) (n_r0 * (uint32_t) 90U));
            
            uint32_t n_deref4 = *n_ref3;
            uint32_t n_cse13 = (uint32_t) (n_deref4 / n_r0);
            int64_t n_local5 = (int64_t) ((int64_t) n_cse13 * (int64_t) 1000);
            int64_t *n_ref6 = &n_local5;
            
            handler_run_chaos_thread_period_90ms(n_ref6);
        }
    }
}

void handler_run_chaos_thread_period_90ms(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_i2c_fuzzer();
    /* run callbacks */
    callback_chaos_thread_period_90ms(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c_fuzzer();
    /* deliver emitters */
    ;
}
