/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "callback_I2C1_ER_IRQHandler.h"

void callback_I2C1_ER_IRQHandler(const int64_t *n_var0)
{
    emitter_I2C1_ER_IRQHandler(n_var0);
}
