/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "I2C1_EV_IRQHandler.h"

void I2C1_EV_IRQHandler(void)
{
    uint16_t n_r0 = ivory_hw_io_read_u16((uint32_t) 1073763332U);
    
    /* reg modify i2c1->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten */
    ivory_hw_io_write_u16((uint32_t) 1073763332U, (uint16_t) ((uint16_t) (n_r0 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U)));
    /* reg set nvic_icer0: setBit nvic_icer_clrena.[31] */
    ivory_hw_io_write_u32((uint32_t) 3758154112U, (uint32_t) ((uint32_t) 1U << (uint32_t) 31U));
}
