/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __GPS_COMMON_H__
#define __GPS_COMMON_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
typedef struct ivory_string_UnusedString {
            uint8_t ivory_string_UnusedString_data[1U];
            int32_t ivory_string_UnusedString_len;
        } ivory_string_UnusedString;
typedef struct ivory_string_GPSString {
            uint8_t ivory_string_GPSString_data[128U];
            int32_t ivory_string_GPSString_len;
        } ivory_string_GPSString;

#ifdef __cplusplus
}
#endif
#endif /* __GPS_COMMON_H__ */
