/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __SPIDRIVERTYPES_H__
#define __SPIDRIVERTYPES_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
typedef struct spi_transaction_request {
            uint8_t tx_device;
            uint8_t tx_buf[128U];
            int32_t tx_len;
        } spi_transaction_request;
typedef struct spi_transaction_result {
            uint8_t resultcode;
            uint8_t rx_buf[128U];
            int32_t rx_idx;
        } spi_transaction_result;

#ifdef __cplusplus
}
#endif
#endif /* __SPIDRIVERTYPES_H__ */
