/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_frameBuffer.h"

int32_t frameBuffer_2_ringbuffer_insert = (int32_t) 0 % 12;

int32_t frameBuffer_2_ringbuffer_remove = (int32_t) 0 % 12;

struct can_message frameBuffer_2_ringbuffer_buf[12U];

bool frameBuffer_2_ringbuffer_push(const struct can_message *n_var0)
{
    int32_t n_deref0 = frameBuffer_2_ringbuffer_insert;
    int32_t n_local1 = (int32_t) 0;
    int32_t *n_ref2 = &n_local1;
    
    if ((bool) (n_deref0 == (int32_t) 11)) {
        *n_ref2 = (int32_t) 0;
    } else {
        *n_ref2 = (int32_t) (n_deref0 + (int32_t) 1) % 12;
    }
    
    int32_t n_deref3 = *n_ref2;
    int32_t n_deref4 = frameBuffer_2_ringbuffer_remove;
    
    if ((bool) (n_deref3 == n_deref4)) {
        return false;
    } else {
        int32_t n_deref5 = frameBuffer_2_ringbuffer_insert;
        
        frameBuffer_2_ringbuffer_buf[n_deref5] = *n_var0;
        
        int32_t n_deref6 = frameBuffer_2_ringbuffer_insert;
        int32_t n_local7 = (int32_t) 0;
        int32_t *n_ref8 = &n_local7;
        
        if ((bool) ((int32_t) 11 == n_deref6)) {
            *n_ref8 = (int32_t) 0;
        } else {
            *n_ref8 = (int32_t) ((int32_t) 1 + n_deref6) % 12;
        }
        
        int32_t n_deref9 = *n_ref8;
        
        frameBuffer_2_ringbuffer_insert = n_deref9;
        return true;
    }
}

bool frameBuffer_2_ringbuffer_pop(struct can_message *n_var0)
{
    int32_t n_deref0 = frameBuffer_2_ringbuffer_insert;
    int32_t n_deref1 = frameBuffer_2_ringbuffer_remove;
    
    if ((bool) (n_deref0 == n_deref1)) {
        return false;
    } else {
        int32_t n_deref2 = frameBuffer_2_ringbuffer_remove;
        
        *n_var0 = frameBuffer_2_ringbuffer_buf[n_deref2];
        
        int32_t n_deref3 = frameBuffer_2_ringbuffer_remove;
        int32_t n_local4 = (int32_t) 0;
        int32_t *n_ref5 = &n_local4;
        
        if ((bool) (n_deref3 == (int32_t) 11)) {
            *n_ref5 = (int32_t) 0;
        } else {
            *n_ref5 = (int32_t) (n_deref3 + (int32_t) 1) % 12;
        }
        
        int32_t n_deref6 = *n_ref5;
        
        frameBuffer_2_ringbuffer_remove = n_deref6;
        return true;
    }
}
