/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_spi1_scheduler.h"

struct mutex lock_spi1_scheduler;

void monitor_init_spi1_scheduler(void)
{
    ivory_freertos_mutex_create(&lock_spi1_scheduler);
}

void monitor_lock_spi1_scheduler(void)
{
    ivory_freertos_mutex_takeblocking(&lock_spi1_scheduler);
}

void monitor_unlock_spi1_scheduler(void)
{
    ivory_freertos_mutex_give(&lock_spi1_scheduler);
}
