/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_10ms.h"

static void emitter_spi1_scheduler_ms5611_chan_158(const struct spi_transaction_request *n_var0);

static void emitter_periodic_chan_175(const struct spi_transaction_request *n_var0);

void callback_spi1_scheduler_ms5611_thread_period_10ms(const struct spi_transaction_request *n_var0)
{
    bool n_deref0 = spi1_scheduler_ms5611_pending;
    
    ASSERTS((bool) !n_deref0);
    spi1_scheduler_ms5611_last_req = *n_var0;
    spi1_scheduler_ms5611_pending = true;
    
    uint32_t n_deref1 = spi1_scheduler_response_task;
    
    if ((bool) (0 == n_deref1)) {
        spi1_scheduler_response_task = (uint32_t) 3U;
        emitter_spi1_scheduler_ms5611_chan_158(&spi1_scheduler_ms5611_last_req);
    }
}

void callback_periodic_thread_period_10ms(const int64_t *n_var0)
{
    uint32_t n_deref0 = continuationMode;
    
    if ((bool) (0 != n_deref0)) {
        if ((bool) (n_deref0 == (uint32_t) 1U)) {
            struct spi_transaction_request n_local1 = {.tx_device =(uint8_t) 2U, .tx_buf ={(uint8_t) 30U}, .tx_len =(int32_t) 1};
            struct spi_transaction_request *n_ref2 = &n_local1;
            
            emitter_periodic_chan_175(n_ref2);
        } else {
            if ((bool) (n_deref0 == (uint32_t) 3U)) {
                struct spi_transaction_request n_local3 = {.tx_device =(uint8_t) 2U, .tx_buf ={(uint8_t) 160U, (uint8_t) 0U, (uint8_t) 0U}, .tx_len =(int32_t) 3};
                struct spi_transaction_request *n_ref4 = &n_local3;
                
                emitter_periodic_chan_175(n_ref4);
            } else {
                if ((bool) (n_deref0 != (uint32_t) 5U)) {
                    if ((bool) (n_deref0 == (uint32_t) 6U)) {
                        struct spi_transaction_request n_local5 = {.tx_device =(uint8_t) 2U, .tx_buf ={(uint8_t) 0U, (uint8_t) 0U, (uint8_t) 0U, (uint8_t) 0U}, .tx_len =(int32_t) 4};
                        struct spi_transaction_request *n_ref6 = &n_local5;
                        
                        emitter_periodic_chan_175(n_ref6);
                    }
                }
            }
        }
    }
}

void callback_request_4_thread_period_10ms(const struct spi_transaction_request *n_var0)
{
    bool n_deref0 = done;
    
    if (n_deref0) {
        done = false;
        reqbuffer = *n_var0;
        
        int32_t n_deref1 = reqbuffer.tx_len;
        
        reqbufferpos = (int32_t) 0;
        resbufferpos = (int32_t) 0;
        resbuffer.rx_idx = n_deref1;
        
        uint8_t n_deref2 = reqbuffer.tx_buf[(int32_t) 0];
        
        reqbufferpos = (int32_t) 1;
        /* selecting device: */
        ;
        
        uint8_t n_deref3 = reqbuffer.tx_device;
        
        ASSERTS((bool) (n_deref3 < (uint8_t) 4U));
        if ((bool) (0 == n_deref3)) {
            mpu6k_devicebegin();
        } else {
            if ((bool) ((uint8_t) 1U == n_deref3)) {
                lsm303d_devicebegin();
            } else {
                if ((bool) ((uint8_t) 2U == n_deref3)) {
                    ms5611_devicebegin();
                } else {
                    if ((bool) (n_deref3 == (uint8_t) 3U)) {
                        l3gd20_devicebegin();
                    }
                }
            }
        }
        /* end selecting configured device */
        ;
        /* reg set spi1->dr: setField spi_dr_data */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073819660U, (uint16_t) ((uint16_t) n_deref2 << 0));
        
        uint16_t n_r4 = ivory_hw_io_read_u16((uint32_t) 1073819652U);
        
        /* reg modify spi1->cr2: setBit spi_cr2_txeie */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073819652U, (uint16_t) (n_r4 | (uint16_t) ((uint16_t) 1U << (uint16_t) 7U)));
    }
}

void emitter_spi1_scheduler_ms5611_chan_158(const struct spi_transaction_request *n_var0)
{
    emitter_spi1_scheduler_ms5611_chan_158_thread_period_10ms_emit(n_var0);
}

void emitter_periodic_chan_175(const struct spi_transaction_request *n_var0)
{
    emitter_periodic_chan_175_thread_period_10ms_emit(n_var0);
}
