/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_fragment_blindly_0x100.h"

uint8_t msg_0x100[80U];

bool in_progress_0x100;

bool abort_pending_0x100;
