/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_controllableVehicleConsumerOutput.h"

struct mutex lock_controllableVehicleConsumerOutput;

void monitor_init_controllableVehicleConsumerOutput(void)
{
    ivory_freertos_mutex_create(&lock_controllableVehicleConsumerOutput);
}

void monitor_lock_controllableVehicleConsumerOutput(void)
{
    ivory_freertos_mutex_takeblocking(&lock_controllableVehicleConsumerOutput);
}

void monitor_unlock_controllableVehicleConsumerOutput(void)
{
    ivory_freertos_mutex_give(&lock_controllableVehicleConsumerOutput);
}
