/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_att_est_sensor_fusion.h"

struct mutex lock_att_est_sensor_fusion;

void monitor_init_att_est_sensor_fusion(void)
{
    ivory_freertos_mutex_create(&lock_att_est_sensor_fusion);
}

void monitor_lock_att_est_sensor_fusion(void)
{
    ivory_freertos_mutex_takeblocking(&lock_att_est_sensor_fusion);
}

void monitor_unlock_att_est_sensor_fusion(void)
{
    ivory_freertos_mutex_give(&lock_att_est_sensor_fusion);
}
