/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_spi1_scheduler.h"

uint32_t spi1_scheduler_response_task = UINT32_MAX;

bool spi1_scheduler_mpu6000_pending;

struct spi_transaction_request spi1_scheduler_mpu6000_last_req;

bool spi1_scheduler_lsm303d_pending;

struct spi_transaction_request spi1_scheduler_lsm303d_last_req;

bool spi1_scheduler_ms5611_pending;

struct spi_transaction_request spi1_scheduler_ms5611_last_req;

bool spi1_scheduler_l3gd20_pending;

struct spi_transaction_request spi1_scheduler_l3gd20_last_req;
