/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_detectMotion.h"

struct mutex lock_detectMotion;

void monitor_init_detectMotion(void)
{
    ivory_freertos_mutex_create(&lock_detectMotion);
}

void monitor_lock_detectMotion(void)
{
    ivory_freertos_mutex_takeblocking(&lock_detectMotion);
}

void monitor_unlock_detectMotion(void)
{
    ivory_freertos_mutex_give(&lock_detectMotion);
}
