/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_altitude_rate_pid_attrServer.h"

struct mutex lock_altitude_rate_pid_attrServer;

void monitor_init_altitude_rate_pid_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_altitude_rate_pid_attrServer);
}

void monitor_lock_altitude_rate_pid_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_altitude_rate_pid_attrServer);
}

void monitor_unlock_altitude_rate_pid_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_altitude_rate_pid_attrServer);
}
