/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_control_law_attrServer.h"

struct mutex lock_control_law_attrServer;

void monitor_init_control_law_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_control_law_attrServer);
}

void monitor_lock_control_law_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_control_law_attrServer);
}

void monitor_unlock_control_law_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_control_law_attrServer);
}
