/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_frameBuffer.h"

struct mutex lock_frameBuffer;

void monitor_init_frameBuffer(void)
{
    ivory_freertos_mutex_create(&lock_frameBuffer);
}

void monitor_lock_frameBuffer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_frameBuffer);
}

void monitor_unlock_frameBuffer(void)
{
    ivory_freertos_mutex_give(&lock_frameBuffer);
}
