/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_arming_request_attrServer.h"

struct mutex lock_arming_request_attrServer;

void monitor_init_arming_request_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_arming_request_attrServer);
}

void monitor_lock_arming_request_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_arming_request_attrServer);
}

void monitor_unlock_arming_request_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_arming_request_attrServer);
}
