/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_can_init.h"

struct mutex lock_can_init;

void monitor_init_can_init(void)
{
    ivory_freertos_mutex_create(&lock_can_init);
}

void monitor_lock_can_init(void)
{
    ivory_freertos_mutex_takeblocking(&lock_can_init);
}

void monitor_unlock_can_init(void)
{
    ivory_freertos_mutex_give(&lock_can_init);
}
