/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_i2c2PeripheralDriver.h"

struct mutex lock_i2c2PeripheralDriver;

void monitor_init_i2c2PeripheralDriver(void)
{
    ivory_freertos_mutex_create(&lock_i2c2PeripheralDriver);
}

void monitor_lock_i2c2PeripheralDriver(void)
{
    ivory_freertos_mutex_takeblocking(&lock_i2c2PeripheralDriver);
}

void monitor_unlock_i2c2PeripheralDriver(void)
{
    ivory_freertos_mutex_give(&lock_i2c2PeripheralDriver);
}
