/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_DMA1_Stream2_IRQHandler.h"

void callback_rx_stream_interrupt_thread_signal_DMA1_Stream2_IRQHandler(const int64_t *n_var0)
{
    /* reg get dma1->lisr:  */
    ;
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073897472U);
    uint8_t n_cse6 = (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 16U) & (uint32_t) 63U) & (uint16_t) 255U);
    bool n_cse10 = (bool) (0 != (uint8_t) ((uint8_t) (n_cse6 >> (uint8_t) 5U) & (uint8_t) 1U));
    
    if (n_cse10) {
        uint32_t n_deref1 = uart4_dma_rx_complete;
        
        uart4_dma_rx_complete = (uint32_t) ((uint32_t) 1U + n_deref1);
    }
    if ((bool) (0 != (uint8_t) ((uint8_t) (n_cse6 >> (uint8_t) 3U) & (uint8_t) 1U))) {
        uint32_t n_deref2 = uart4_dma_rx_transfer_err;
        
        uart4_dma_rx_transfer_err = (uint32_t) ((uint32_t) 1U + n_deref2);
    }
    if ((bool) (0 != (uint8_t) ((uint8_t) (n_cse6 >> (uint8_t) 2U) & (uint8_t) 1U))) {
        uint32_t n_deref3 = uart4_dma_rx_direct_err;
        
        uart4_dma_rx_direct_err = (uint32_t) ((uint32_t) 1U + n_deref3);
    }
    /* reg set dma1->lifcr: setBit dma_lifcr_stream2.dma_clearisrflag_CTCIF, setBit dma_lifcr_stream2.dma_clearisrflag_CHTIF, setBit dma_lifcr_stream2.dma_clearisrflag_CTEIF, setBit dma_lifcr_stream2.dma_clearisrflag_CDMEIF, setBit dma_lifcr_stream2.dma_clearisrflag_CFEIF */
    ivory_hw_io_write_u32((uint32_t) 1073897480U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 1U << (uint32_t) 21U) | (uint32_t) ((uint32_t) 1U << (uint32_t) 20U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 19U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 18U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 16U)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
    
    /* reg modify dma1->s2cr: setField dma_sxcr_tcie, setField dma_sxcr_htie, setField dma_sxcr_teie, setField dma_sxcr_dmeie */
    ivory_hw_io_write_u32((uint32_t) 1073897536U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_r4 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 4U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 4U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 3U)) | (uint32_t) ((uint32_t) 0 << (uint32_t) 3U)) &
                                                                                                  (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 2U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 2U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 1U)));
    if (n_cse10) {
        /* reg get dma1->s2cr:  */
        ;
        
        uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
        bool n_let6 = (bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r5 >> (uint32_t) 19U) & (uint32_t) 1U) & (uint16_t) 255U));
        
        if (n_let6) {
            uart4_dma_rx1_buf.ivory_string_GPSString_len = (int32_t) 127;
            uart4_dma_isr_buf = uart4_dma_rx1_buf;
        } else {
            uart4_dma_rx0_buf.ivory_string_GPSString_len = (int32_t) 127;
            uart4_dma_isr_buf = uart4_dma_rx0_buf;
        }
    }
    /* reg set nvic_iser0: setBit nvic_iser_setena.[13] */
    ivory_hw_io_write_u32((uint32_t) 3758153984U, (uint32_t) ((uint32_t) 1U << (uint32_t) 13U));
}
