/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_CAN1_TX_IRQHandler.h"

static void emitter_fragment_done_chan_144(const uint8_t n_var0[80U]);

static void emitter_fragment_complete_0x100_chan_2(const struct can_message *n_var0);

static void emitter_fragment_complete_0x100_chan_146(const bool *n_var0);

static void emitter_fragment_req_0x100_chan_2(const struct can_message *n_var0);

static void emitter_tx_irq_chan_3(const bool *n_var0);

void callback_fragment_done_thread_signal_CAN1_TX_IRQHandler(const bool *n_var0)
{
    bool n_deref0 = abort_pending_0x100;
    
    if (n_deref0) {
        emitter_fragment_done_chan_144(msg_0x100);
        abort_pending_0x100 = false;
    }
    in_progress_0x100 = n_deref0;
}

void callback_fragment_complete_0x100_thread_signal_CAN1_TX_IRQHandler(const bool *n_var0)
{
    bool n_deref0 = *n_var0;
    
    if ((bool) !n_deref0) {
        bool n_local1 = false;
        bool *n_ref2 = &n_local1;
        
        emitter_fragment_complete_0x100_chan_146(n_ref2);
        fragment_sent_0x100 = (uint8_t) 0U;
        fragment_aborting_0x100 = false;
    } else {
        uint8_t n_deref3 = fragment_sent_0x100;
        
        ASSERTS((bool) (n_deref3 > 0));
        
        uint16_t n_cse2 = (uint16_t) n_deref3;
        
        if ((bool) ((uint16_t) 80U <= (uint16_t) ((uint16_t) 8U * n_cse2))) {
            bool n_local4 = true;
            bool *n_ref5 = &n_local4;
            
            emitter_fragment_complete_0x100_chan_146(n_ref5);
            fragment_sent_0x100 = (uint8_t) 0U;
            fragment_aborting_0x100 = false;
        } else {
            bool n_deref6 = fragment_aborting_0x100;
            
            if (n_deref6) {
                bool n_local7 = false;
                bool *n_ref8 = &n_local7;
                
                emitter_fragment_complete_0x100_chan_146(n_ref8);
                fragment_sent_0x100 = (uint8_t) 0U;
                fragment_aborting_0x100 = false;
            } else {
                uint8_t n_cse26 = (uint8_t) ((uint8_t) 80U - (uint8_t) (n_deref3 * (uint8_t) 8U));
                uint8_t n_cse28 = (uint8_t) ((bool) (n_cse26 > (uint8_t) 8U) ? (uint8_t) 8U : n_cse26);
                struct can_message n_local9 = {.can_message_id =(uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (uint16_t) ((uint16_t) (n_cse2 + (uint16_t) 256U) & (uint16_t) 2047U) << (uint32_t) 18U) & (uint32_t) 536870911U) << (uint32_t) 2U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)) | (uint32_t) ((uint32_t) 0 << 0)), .can_message_len =(int32_t) n_cse28 % 9};
                struct can_message *n_ref10 = &n_local9;
                int32_t n_cse37 = (int32_t) (uint8_t) (n_cse28 - (uint8_t) 1U) % 8;
                
                COMPILER_ASSERTS((bool) ((bool) (n_cse37 < (int32_t) 8) && (bool) ((int32_t) 0 <= n_cse37)));
                for (int32_t n_ix11 = (int32_t) 0; n_ix11 <= n_cse37; n_ix11++) {
                    n_ref10->can_message_buf[n_ix11] = fragment_buf_0x100[(int32_t) ((int32_t) ((int32_t) 8 * (int32_t) n_deref3) + n_ix11) % 80];
                }
                fragment_sent_0x100 = (uint8_t) (n_deref3 + (uint8_t) 1U);
                emitter_fragment_complete_0x100_chan_2(n_ref10);
            }
        }
    }
}

void callback_fragment_req_0x100_thread_signal_CAN1_TX_IRQHandler(const uint8_t n_var0[80U])
{
    uint8_t n_deref0 = fragment_sent_0x100;
    
    ASSERTS((bool) (0 == n_deref0));
    for (int32_t n_ix1 = (int32_t) 0; n_ix1 <= (int32_t) 79; n_ix1++) {
        ivory_serialize_pack_uint8_be((uint8_t *) fragment_buf_0x100, (uint32_t) n_ix1, &n_var0[n_ix1]);
    }
    
    struct can_message n_local2 = {.can_message_id =(uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 256U << (uint32_t) 18U) & (uint32_t) 536870911U) << (uint32_t) 2U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)) | (uint32_t) ((uint32_t) 0 << 0)), .can_message_len =(int32_t) 8};
    struct can_message *n_ref3 = &n_local2;
    
    for (int32_t n_ix4 = (int32_t) 0; n_ix4 <= (int32_t) 7; n_ix4++) {
        n_ref3->can_message_buf[n_ix4] = fragment_buf_0x100[n_ix4 % 80];
    }
    fragment_sent_0x100 = (uint8_t) 1U;
    emitter_fragment_req_0x100_chan_2(n_ref3);
}

void callback_tx_irq_thread_signal_CAN1_TX_IRQHandler(const int64_t *n_var0)
{
    /* reg get can1->tsr:  */
    ;
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073767432U);
    
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> 0) & (uint32_t) 1U) & (uint16_t) 255U))) {
        /* reg set can1->tsr: setBit can_tsr_rqcp0 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073767432U, (uint32_t) ((uint32_t) 1U << 0));
        
        bool n_local1 = (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 1U) & (uint32_t) 1U) & (uint16_t) 255U));
        bool *n_ref2 = &n_local1;
        
        emitter_tx_irq_chan_3(n_ref2);
    }
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 8U) & (uint32_t) 1U) & (uint16_t) 255U))) {
        /* reg set can1->tsr: setBit can_tsr_rqcp1 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073767432U, (uint32_t) ((uint32_t) 1U << (uint32_t) 8U));
        
        bool n_local3 = (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 9U) & (uint32_t) 1U) & (uint16_t) 255U));
        bool *n_ref4 = &n_local3;
    }
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 16U) & (uint32_t) 1U) & (uint16_t) 255U))) {
        /* reg set can1->tsr: setBit can_tsr_rqcp2 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073767432U, (uint32_t) ((uint32_t) 1U << (uint32_t) 16U));
        
        bool n_local5 = (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 17U) & (uint32_t) 1U) & (uint16_t) 255U));
        bool *n_ref6 = &n_local5;
    }
    /* reg set nvic_iser0: setBit nvic_iser_setena.[19] */
    ivory_hw_io_write_u32((uint32_t) 3758153984U, (uint32_t) ((uint32_t) 1U << (uint32_t) 19U));
}

void callback_request_thread_signal_CAN1_TX_IRQHandler(const struct can_message *n_var0)
{
    /* reg get can1->tsr:  */
    ;
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073767432U);
    
    /* mailbox must be empty */
    ASSERTS((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 26U) & (uint32_t) 1U) & (uint16_t) 255U)));
    /* any completed request must have already been reported */
    ASSERTS((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> 0) & (uint32_t) 1U) & (uint16_t) 255U)));
    
    uint32_t n_deref1 = n_var0->can_message_id;
    int32_t n_deref2 = n_var0->can_message_len;
    const uint8_t *n_cse20 = n_var0->can_message_buf;
    uint8_t n_deref3 = n_cse20[(int32_t) 0];
    uint8_t n_deref4 = n_cse20[(int32_t) 1];
    uint8_t n_deref5 = n_cse20[(int32_t) 2];
    uint8_t n_deref6 = n_cse20[(int32_t) 3];
    uint8_t n_deref7 = n_cse20[(int32_t) 4];
    uint8_t n_deref8 = n_cse20[(int32_t) 5];
    uint8_t n_deref9 = n_cse20[(int32_t) 6];
    uint8_t n_deref10 = n_cse20[(int32_t) 7];
    uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073767812U);
    
    /* reg modify can1->tdt0r: clearBit can_tdtr_tgt, setField can_tdtr_dlc */
    ivory_hw_io_write_u32((uint32_t) 1073767812U, (uint32_t) ((uint32_t) ((uint32_t) (n_r11 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 8U)) & (uint32_t) ~(uint32_t) ((uint32_t) 15U << 0)) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) ((bool) ((bool) (n_deref2 <= (int32_t) UINT8_MAX) && (bool) (n_deref2 >= (int32_t) 0)) ? (uint8_t) n_deref2 : 0) & (uint8_t) 15U) << 0)));
    /* reg set can1->tdl0r: setField can_tdlr_data0, setField can_tdlr_data1, setField can_tdlr_data2, setField can_tdlr_data3 */
    ;
    
    uint32_t n_cse64 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 8U);
    uint32_t n_cse71 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 16U);
    uint32_t n_cse78 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 24U);
    
    ivory_hw_io_write_u32((uint32_t) 1073767816U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) n_deref3 << 0) & n_cse64) | (uint32_t) ((uint32_t) n_deref4 << (uint32_t) 8U)) & n_cse71) | (uint32_t) ((uint32_t) n_deref5 << (uint32_t) 16U)) & n_cse78) | (uint32_t) ((uint32_t) n_deref6 << (uint32_t) 24U)));
    /* reg set can1->tdh0r: setField can_tdhr_data4, setField can_tdhr_data5, setField can_tdhr_data6, setField can_tdhr_data7 */
    ivory_hw_io_write_u32((uint32_t) 1073767820U, (uint32_t) ((uint32_t) (n_cse78 & (uint32_t) ((uint32_t) (n_cse71 & (uint32_t) ((uint32_t) (n_cse64 & (uint32_t) ((uint32_t) n_deref7 << 0)) | (uint32_t) ((uint32_t) n_deref8 << (uint32_t) 8U))) | (uint32_t) ((uint32_t) n_deref9 << (uint32_t) 16U))) | (uint32_t) ((uint32_t) n_deref10 << (uint32_t) 24U)));
    /* reg set can1->ti0r: setField can_tir_id, setField can_tir_ide, setField can_tir_rtr, setBit can_tir_txrq */
    ivory_hw_io_write_u32((uint32_t) 1073767808U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_deref1 >> (uint32_t) 2U) & (uint32_t) 536870911U) << (uint32_t) 3U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 2U)) | (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_deref1 >> (uint32_t) 1U) &
                                                                                                                                                                                                                                                                                                                                                         (uint32_t) 1U) & (uint16_t) 255U) << (uint32_t) 2U)) &
                                                                                      (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) | (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_deref1 >> 0) & (uint32_t) 1U) & (uint16_t) 255U) << (uint32_t) 1U)) | (uint32_t) ((uint32_t) 1U << 0)));
}

void emitter_fragment_done_chan_144(const uint8_t n_var0[80U])
{
    emitter_fragment_done_chan_144_thread_signal_CAN1_TX_IRQHandler_emit(n_var0);
}

void emitter_fragment_complete_0x100_chan_2(const struct can_message *n_var0)
{
    emitter_fragment_complete_0x100_chan_2_thread_signal_CAN1_TX_IRQHandler_emit(n_var0);
}

void emitter_fragment_complete_0x100_chan_146(const bool *n_var0)
{
    emitter_fragment_complete_0x100_chan_146_thread_signal_CAN1_TX_IRQHandler_emit(n_var0);
}

void emitter_fragment_req_0x100_chan_2(const struct can_message *n_var0)
{
    emitter_fragment_req_0x100_chan_2_thread_signal_CAN1_TX_IRQHandler_emit(n_var0);
}

void emitter_tx_irq_chan_3(const bool *n_var0)
{
    emitter_tx_irq_chan_3_thread_signal_CAN1_TX_IRQHandler_emit(n_var0);
}
