/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_accel_output_attrServer.h"

struct mutex lock_accel_output_attrServer;

void monitor_init_accel_output_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_accel_output_attrServer);
}

void monitor_lock_accel_output_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_accel_output_attrServer);
}

void monitor_unlock_accel_output_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_accel_output_attrServer);
}
