/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_I2C2_EV_IRQHandler.h"

static void emitter_i2c2_event_irq_chan_191(const struct i2c_transaction_result *n_var0);

void callback_i2c_response_thread_signal_I2C2_EV_IRQHandler(const struct i2c_transaction_result *n_var0)
{
    bool n_deref0 = expect_response;
    
    if (n_deref0) {
        uint8_t n_deref1 = n_var0->resultcode;
        
        if ((bool) (n_deref1 > 0)) {
            error = (uint8_t) 3U;
        }
    } else {
        error = (uint8_t) 2U;
    }
    expect_response = false;
}

void callback_i2c2_event_irq_thread_signal_I2C2_EV_IRQHandler(const int64_t *n_var0)
{
    int64_t n_r0 = tower_get_time();
    
    i2c2_last_event = n_r0;
    
    uint8_t n_deref1 = i2c2_driverstate;
    
    /* reg get i2c2->sr1:  */
    ;
    
    uint16_t n_r2 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
    
    if ((bool) (n_deref1 == (uint8_t) 1U)) {
        /* i2cEV5 */
        ;
        if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> 0) & (uint16_t) 1U))) {
            /* master mode, busy bus, start bit set */
            ;
            
            uint8_t n_deref3 = i2c2_reqbuffer.tx_addr;
            int32_t n_deref4 = i2c2_reqbufferpos;
            int32_t n_deref5 = i2c2_reqbuffer.tx_len;
            uint8_t n_cse14 = (uint8_t) ((uint8_t) 2U * n_deref3);
            uint8_t n_let6 = (uint8_t) ((bool) ((int32_t) (n_deref5 - n_deref4) % 128 > 0) ? n_cse14 : (uint8_t) ((uint8_t) 1U + n_cse14));
            
            i2c2_driverstate = (uint8_t) 2U;
            
            uint16_t n_r7 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
            
            /* reg modify i2c2->dr: setField i2c_dr_data */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073764368U, (uint16_t) ((uint16_t) (n_r7 & (uint16_t) ~(uint16_t) ((uint16_t) 255U << 0)) | (uint16_t) ((uint16_t) n_let6 << 0)));
        } else {
            if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 1U) & (uint16_t) 1U))) {
                /* addr bit shouldn't be set unless start bit is */
                ;
                
                uint16_t n_r8 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                
                /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                ;
                
                uint16_t n_cse45 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                uint16_t n_cse48 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                uint16_t n_cse51 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                
                ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_r8 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                             (uint16_t) 12U)) &
                                                                                                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & n_cse45) & n_cse48) & n_cse51) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                  (uint16_t) 6U)) &
                                                                                                                          (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                              0)));
                
                uint16_t n_r9 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                
                /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                ;
                ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse51 & n_cse48) & n_cse45) & n_r9));
                
                uint8_t n_deref10 = i2c2_driverstate;
                
                if ((bool) (0 != n_deref10)) {
                    i2c2_driverstate = (uint8_t) 0U;
                    i2c2_resbuffer.resultcode = (uint8_t) 1U;
                    
                    uint32_t n_deref11 = i2c2_error_run;
                    
                    i2c2_error_run = (uint32_t) ((uint32_t) 1U + n_deref11);
                    emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                }
            }
        }
    } else {
        if ((bool) ((uint8_t) 2U == n_deref1)) {
            /* i2cEV6 */
            ;
            if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> 0) & (uint16_t) 1U))) {
                /* start bit should have been cleared when writing addr */
                ;
                
                uint16_t n_r12 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                
                /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                ;
                
                uint16_t n_cse106 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                uint16_t n_cse108 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                uint16_t n_cse110 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                
                ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) &
                                                                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) &
                                                                                                                                                                          (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & n_cse106) & n_cse108) & n_cse110) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) &
                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r12));
                
                uint16_t n_r13 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                
                /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                ;
                ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse106 & n_cse108) & n_cse110) & n_r13));
                
                uint8_t n_deref14 = i2c2_driverstate;
                
                if ((bool) (0 != n_deref14)) {
                    i2c2_driverstate = (uint8_t) 0U;
                    i2c2_resbuffer.resultcode = (uint8_t) 1U;
                    
                    uint32_t n_deref15 = i2c2_error_run;
                    
                    i2c2_error_run = (uint32_t) ((uint32_t) 1U + n_deref15);
                    emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                }
            } else {
                if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 1U) & (uint16_t) 1U))) {
                    /* addr bit set, ready to start sending/receiving */
                    ;
                    
                    int32_t n_deref16 = i2c2_reqbufferpos;
                    int32_t n_deref17 = i2c2_reqbuffer.tx_len;
                    int32_t n_deref18 = i2c2_resbufferpos;
                    int32_t n_deref19 = i2c2_reqbuffer.rx_len;
                    int32_t n_cse152 = (int32_t) (n_deref17 - n_deref16) % 128;
                    
                    if ((bool) (n_cse152 > 0)) {
                        /* tx: clear addr */
                        ;
                        /* reg get i2c2->sr2:  */
                        ;
                        
                        uint16_t n_r20 = ivory_hw_io_read_u16((uint32_t) 1073764376U);
                        uint8_t n_deref21 = i2c2_reqbuffer.tx_buf[n_deref16];
                        
                        i2c2_reqbufferpos = (int32_t) ((int32_t) 1 + n_deref16) % 128;
                        
                        uint16_t n_r22 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                        
                        /* reg modify i2c2->dr: setField i2c_dr_data */
                        ;
                        ivory_hw_io_write_u16((uint32_t) 1073764368U, (uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 255U << 0) & n_r22) | (uint16_t) ((uint16_t) n_deref21 << 0)));
                        if ((bool) (n_cse152 == (int32_t) 1)) {
                            i2c2_driverstate = (uint8_t) 8U;
                        } else {
                            i2c2_driverstate = (uint8_t) 7U;
                        }
                    } else {
                        int32_t n_cse170 = (int32_t) (n_deref19 - n_deref18) % 128;
                        
                        if ((bool) (n_cse170 > (int32_t) 2)) {
                            /* rx: send an ack until cleared */
                            ;
                            
                            uint16_t n_r23 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                            
                            /* reg modify i2c2->cr1: setBit i2c_cr1_ack */
                            ;
                            ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 10U) | n_r23));
                            if ((bool) (n_cse170 == (int32_t) 3)) {
                                i2c2_driverstate = (uint8_t) 4U;
                            } else {
                                i2c2_driverstate = (uint8_t) 3U;
                            }
                        } else {
                            if ((bool) (n_cse170 == (int32_t) 2)) {
                                /* rx: special case read 2 bytes (pg841) */
                                ;
                                
                                uint16_t n_r24 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                
                                /* reg modify i2c2->cr1: clearBit i2c_cr1_ack, setBit i2c_cr1_pos */
                                ;
                                ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 11U) | (uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U) & n_r24)));
                                i2c2_driverstate = (uint8_t) 5U;
                            } else {
                                if ((bool) ((int32_t) 1 == n_cse170)) {
                                    /* rx: 1 byte read, set nack now (Figure 244) */
                                    ;
                                    
                                    uint16_t n_r25 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                    
                                    /* reg modify i2c2->cr1: clearBit i2c_cr1_ack */
                                    ;
                                    ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U) & n_r25));
                                    i2c2_driverstate = (uint8_t) 6U;
                                } else {
                                    uint16_t n_r26 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                                    
                                    /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                                    ;
                                    
                                    uint16_t n_cse206 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                                    uint16_t n_cse208 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                                    uint16_t n_cse210 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                                    
                                    ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                           (uint16_t) 2U)) &
                                                                                                                                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                (uint16_t) 6U)) &
                                                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & n_cse206) & n_cse208) & n_cse210) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                 (uint16_t) 12U)) &
                                                                                                                      (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r26));
                                    
                                    uint16_t n_r27 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                                    
                                    /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                                    ;
                                    ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse206 & n_cse208) & n_cse210) & n_r27));
                                    
                                    uint8_t n_deref28 = i2c2_driverstate;
                                    
                                    if ((bool) (0 != n_deref28)) {
                                        i2c2_driverstate = (uint8_t) 0U;
                                        i2c2_resbuffer.resultcode = (uint8_t) 0U;
                                        i2c2_error_run = (uint32_t) 0U;
                                        emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                                    }
                                }
                            }
                        }
                    }
                    /* reg get i2c2->sr2:  */
                    ;
                    
                    uint16_t n_r30 = ivory_hw_io_read_u16((uint32_t) 1073764376U);
                }
            }
        } else {
            if ((bool) (n_deref1 == (uint8_t) 3U)) {
                /* i2cEV7 */
                ;
                if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 6U) & (uint16_t) 1U))) {
                    int32_t n_deref31 = i2c2_resbufferpos;
                    int32_t n_deref32 = i2c2_reqbuffer.rx_len;
                    int32_t n_cse252 = (int32_t) (n_deref32 - n_deref31) % 128;
                    
                    if ((bool) (n_cse252 == (int32_t) 4)) {
                        i2c2_driverstate = (uint8_t) 4U;
                    }
                    /* reg get i2c2->dr:  */
                    ;
                    
                    uint16_t n_r33 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                    uint8_t n_let34 = (uint8_t) (uint16_t) ((uint16_t) (n_r33 >> 0) & (uint16_t) 255U);
                    
                    i2c2_resbuffer.rx_buf[n_deref31] = n_let34;
                    i2c2_resbufferpos = (int32_t) ((int32_t) 1 + n_deref31) % 128;
                    if ((bool) ((int32_t) 1 == n_cse252)) {
                        uint16_t n_r35 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                        
                        /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                        ;
                        
                        uint16_t n_cse281 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                        uint16_t n_cse283 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                        uint16_t n_cse285 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                        
                        ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                               (uint16_t) 2U)) &
                                                                                                                                                                                                                      (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) &
                                                                                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & n_cse281) & n_cse283) & n_cse285) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) &
                                                                                                          (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r35));
                        
                        uint16_t n_r36 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                        
                        /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                        ;
                        ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse281 & n_cse283) & n_cse285) & n_r36));
                        
                        uint8_t n_deref37 = i2c2_driverstate;
                        
                        if ((bool) (0 != n_deref37)) {
                            i2c2_driverstate = (uint8_t) 0U;
                            i2c2_resbuffer.resultcode = (uint8_t) 0U;
                            i2c2_error_run = (uint32_t) 0U;
                            emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                        }
                    }
                }
            } else {
                if ((bool) (n_deref1 == (uint8_t) 4U)) {
                    /* i2cEV7_N2 */
                    ;
                    if ((bool) ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 6U) & (uint16_t) 1U)) && (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 2U) & (uint16_t) 1U)))) {
                        int32_t n_deref39 = i2c2_resbufferpos;
                        int32_t n_deref40 = i2c2_reqbuffer.rx_len;
                        
                        ASSERTS((bool) ((int32_t) 3 == (int32_t) (n_deref40 - n_deref39) % 128));
                        
                        uint16_t n_r41 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                        
                        /* reg modify i2c2->cr1: clearBit i2c_cr1_ack */
                        ;
                        ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U) & n_r41));
                        i2c2_driverstate = (uint8_t) 5U;
                        /* reg get i2c2->dr:  */
                        ;
                        
                        uint16_t n_r42 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                        uint8_t n_let43 = (uint8_t) (uint16_t) ((uint16_t) (n_r42 >> 0) & (uint16_t) 255U);
                        
                        i2c2_resbuffer.rx_buf[n_deref39] = n_let43;
                        i2c2_resbufferpos = (int32_t) ((int32_t) 1 + n_deref39) % 128;
                    }
                } else {
                    if ((bool) (n_deref1 == (uint8_t) 5U)) {
                        /* i2cEV7_N1 */
                        ;
                        if ((bool) ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 6U) & (uint16_t) 1U)) && (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 2U) & (uint16_t) 1U)))) {
                            uint16_t n_r44 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                            
                            /* reg modify i2c2->cr1: clearBit i2c_cr1_pos */
                            ;
                            ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U) & n_r44));
                            
                            int32_t n_deref45 = i2c2_resbufferpos;
                            int32_t n_deref46 = i2c2_reqbuffer.rx_len;
                            
                            ASSERTS((bool) ((int32_t) 2 == (int32_t) (n_deref46 - n_deref45) % 128));
                            
                            uint16_t n_r47 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                            
                            /* reg modify i2c2->cr1: setBit i2c_cr1_stop */
                            ;
                            ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 9U) | n_r47));
                            for (int32_t n_ix48 = (int32_t) 14; n_ix48 >= (int32_t) 0; n_ix48--) {
                                /* reg get i2c2->cr1:  */
                                ;
                                
                                uint16_t n_r49 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                
                                if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (n_r49 >> (uint16_t) 9U) & (uint16_t) 1U))) {
                                    break;
                                }
                            }
                            i2c2_driverstate = (uint8_t) 3U;
                            /* reg get i2c2->dr:  */
                            ;
                            
                            uint16_t n_r50 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                            uint8_t n_let51 = (uint8_t) (uint16_t) ((uint16_t) (n_r50 >> 0) & (uint16_t) 255U);
                            
                            i2c2_resbuffer.rx_buf[n_deref45] = n_let51;
                            i2c2_resbufferpos = (int32_t) ((int32_t) 1 + n_deref45) % 128;
                        }
                    } else {
                        if ((bool) (n_deref1 == (uint8_t) 6U)) {
                            /* i2cEV7_rx1 */
                            ;
                            if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 6U) & (uint16_t) 1U))) {
                                uint16_t n_r52 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                
                                /* reg modify i2c2->cr1: setBit i2c_cr1_stop */
                                ;
                                
                                uint16_t n_cse408 = (uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                                
                                ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) (n_cse408 | n_r52));
                                for (int32_t n_ix53 = (int32_t) 14; n_ix53 >= (int32_t) 0; n_ix53--) {
                                    /* reg get i2c2->cr1:  */
                                    ;
                                    
                                    uint16_t n_r54 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                    
                                    if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (n_r54 >> (uint16_t) 9U) & (uint16_t) 1U))) {
                                        break;
                                    }
                                }
                                
                                int32_t n_deref55 = i2c2_resbufferpos;
                                int32_t n_deref56 = i2c2_reqbuffer.rx_len;
                                
                                ASSERTS((bool) ((int32_t) 1 == (int32_t) (n_deref56 - n_deref55) % 128));
                                /* reg get i2c2->dr:  */
                                ;
                                
                                uint16_t n_r57 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                                uint8_t n_let58 = (uint8_t) (uint16_t) ((uint16_t) (n_r57 >> 0) & (uint16_t) 255U);
                                
                                i2c2_resbuffer.rx_buf[n_deref55] = n_let58;
                                i2c2_resbufferpos = (int32_t) ((int32_t) 1 + n_deref55) % 128;
                                
                                uint16_t n_r59 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                                
                                /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                                ;
                                
                                uint16_t n_cse454 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                                uint16_t n_cse455 = (uint16_t) ~n_cse408;
                                uint16_t n_cse457 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                                
                                ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                       (uint16_t) 2U)) &
                                                                                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) &
                                                                                                                                                                                          (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & n_cse454) & n_cse455) & n_cse457) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) &
                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r59));
                                
                                uint16_t n_r60 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                                
                                /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                                ;
                                ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse454 & n_cse455) & n_cse457) & n_r60));
                                
                                uint8_t n_deref61 = i2c2_driverstate;
                                
                                if ((bool) (0 != n_deref61)) {
                                    i2c2_driverstate = (uint8_t) 0U;
                                    i2c2_resbuffer.resultcode = (uint8_t) 0U;
                                    i2c2_error_run = (uint32_t) 0U;
                                    emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                                }
                            }
                        } else {
                            if ((bool) (n_deref1 == (uint8_t) 7U)) {
                                /* i2cEV8 */
                                ;
                                if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 7U) & (uint16_t) 1U))) {
                                    int32_t n_deref63 = i2c2_reqbufferpos;
                                    int32_t n_deref64 = i2c2_reqbuffer.tx_len;
                                    int32_t n_cse499 = (int32_t) (n_deref64 - n_deref63) % 128;
                                    
                                    ASSERTS((bool) (n_cse499 > 0));
                                    if ((bool) ((int32_t) 1 == n_cse499)) {
                                        i2c2_driverstate = (uint8_t) 8U;
                                    }
                                    
                                    uint8_t n_deref65 = i2c2_reqbuffer.tx_buf[n_deref63];
                                    
                                    i2c2_reqbufferpos = (int32_t) ((int32_t) 1 + n_deref63) % 128;
                                    
                                    uint16_t n_r66 = ivory_hw_io_read_u16((uint32_t) 1073764368U);
                                    
                                    /* reg modify i2c2->dr: setField i2c_dr_data */
                                    ;
                                    ivory_hw_io_write_u16((uint32_t) 1073764368U, (uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 255U << 0) & n_r66) | (uint16_t) ((uint16_t) n_deref65 << 0)));
                                }
                            } else {
                                if ((bool) (n_deref1 == (uint8_t) 8U)) {
                                    /* i2cEV8_2 */
                                    ;
                                    if ((bool) ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 7U) & (uint16_t) 1U)) && (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 2U) & (uint16_t) 1U)))) {
                                        int32_t n_deref67 = i2c2_reqbufferpos;
                                        int32_t n_deref68 = i2c2_reqbuffer.tx_len;
                                        int32_t n_deref69 = i2c2_resbufferpos;
                                        int32_t n_deref70 = i2c2_reqbuffer.rx_len;
                                        
                                        ASSERTS((bool) (0 == (int32_t) (n_deref68 - n_deref67) % 128));
                                        if ((bool) ((int32_t) (n_deref70 - n_deref69) % 128 > 0)) {
                                            i2c2_driverstate = (uint8_t) 1U;
                                            
                                            uint16_t n_r71 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                            
                                            /* reg modify i2c2->cr1: setBit i2c_cr1_start */
                                            ;
                                            ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 8U) | n_r71));
                                            for (int32_t n_ix72 = (int32_t) 14; n_ix72 >= (int32_t) 0; n_ix72--) {
                                                /* reg get i2c2->cr1:  */
                                                ;
                                                
                                                uint16_t n_r73 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                                
                                                if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (n_r73 >> (uint16_t) 8U) & (uint16_t) 1U))) {
                                                    break;
                                                }
                                            }
                                        } else {
                                            uint16_t n_r74 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                            
                                            /* reg modify i2c2->cr1: setBit i2c_cr1_stop */
                                            ;
                                            
                                            uint16_t n_cse557 = (uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
                                            
                                            ivory_hw_io_write_u16((uint32_t) 1073764352U, (uint16_t) (n_cse557 | n_r74));
                                            for (int32_t n_ix75 = (int32_t) 14; n_ix75 >= (int32_t) 0; n_ix75--) {
                                                /* reg get i2c2->cr1:  */
                                                ;
                                                
                                                uint16_t n_r76 = ivory_hw_io_read_u16((uint32_t) 1073764352U);
                                                
                                                if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (n_r76 >> (uint16_t) 9U) & (uint16_t) 1U))) {
                                                    break;
                                                }
                                            }
                                            
                                            uint16_t n_r77 = ivory_hw_io_read_u16((uint32_t) 1073764372U);
                                            
                                            /* reg modify i2c2->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
                                            ;
                                            
                                            uint16_t n_cse589 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
                                            uint16_t n_cse590 = (uint16_t) ~n_cse557;
                                            uint16_t n_cse592 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
                                            
                                            ivory_hw_io_write_u16((uint32_t) 1073764372U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) &
                                                                                                                                                                                                                                                      (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) &
                                                                                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) &
                                                                                                                                                                                          n_cse589) & n_cse590) & n_cse592) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                              (uint16_t) 14U)) &
                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r77));
                                            
                                            uint16_t n_r78 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
                                            
                                            /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
                                            ;
                                            ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse589 & n_cse590) & n_cse592) & n_r78));
                                            
                                            uint8_t n_deref79 = i2c2_driverstate;
                                            
                                            if ((bool) (0 != n_deref79)) {
                                                i2c2_driverstate = (uint8_t) 0U;
                                                i2c2_resbuffer.resultcode = (uint8_t) 0U;
                                                i2c2_error_run = (uint32_t) 0U;
                                                emitter_i2c2_event_irq_chan_191(&i2c2_resbuffer);
                                            }
                                        }
                                    }
                                } else {
                                    if ((bool) (0 == n_deref1)) {
                                        /* i2cInactive */
                                        ;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if ((bool) (0 != n_deref1)) {
        uint16_t n_r81 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
        
        /* reg modify i2c2->cr2: setBit i2c_cr2_itbufen, setBit i2c_cr2_itevten, setBit i2c_cr2_iterren */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) 1U << (uint16_t) 8U) | (uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) | n_r81));
    } else {
        uint16_t n_r82 = ivory_hw_io_read_u16((uint32_t) 1073764356U);
        
        /* reg modify i2c2->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073764356U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) & n_r82));
    }
    /* reg set nvic_iser1: setBit nvic_iser_setena.[1] */
    ivory_hw_io_write_u32((uint32_t) 3758153988U, (uint32_t) ((uint32_t) 1U << (uint32_t) 1U));
}

void emitter_i2c2_event_irq_chan_191(const struct i2c_transaction_result *n_var0)
{
    emitter_i2c2_event_irq_chan_191_thread_signal_I2C2_EV_IRQHandler_emit(n_var0);
}
