/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_lsm303dSensorManager.h"

bool initialized = false;

struct magnetometer_sample mag_s;

struct accelerometer_sample accel_s;

struct spi_transaction_result last_value_3;

struct lsm303d_coroutine_continuation lsm303d_coroutine_cont;
