/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_motor_output_attrServer.h"

struct mutex lock_motor_output_attrServer;

void monitor_init_motor_output_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_motor_output_attrServer);
}

void monitor_lock_motor_output_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_motor_output_attrServer);
}

void monitor_unlock_motor_output_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_motor_output_attrServer);
}
