/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_33ms.h"

static void emitter_rx_flush_chan_150(const struct ivory_string_GPSString *n_var0);

static void emitter_write_gps_output_attr_chan_37(const struct position_sample *n_var0);

static void emitter_ublox_istream_chan_147(const struct position_sample *n_var0);

static void emitter_uart4_buf_rx_chan_152(const uint8_t *n_var0);

void callback_rx_flush_thread_period_33ms(const int64_t *n_var0)
{
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
            
            /* reg modify dma1->s2cr: clearBit dma_sxcr_en */
            ;
            ivory_hw_io_write_u32((uint32_t) 1073897536U, (uint32_t) (n_r0 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)));
            /* reg get dma1->s2cr:  */
            ;
            
            uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
            
            if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r1 >> 0) & (uint32_t) 1U) & (uint16_t) 255U))) {
                break;
            }
        }
    }
    /* reg get dma1->s2ndtr:  */
    ;
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073897540U);
    
    /* reg set dma1->s2ndtr: setField dma_sxndtr_ndt */
    ivory_hw_io_write_u32((uint32_t) 1073897540U, (uint32_t) ((uint32_t) 127U << 0));
    /* reg get dma1->s2cr:  */
    ;
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
    
    /* reg set dma1->lifcr: setBit dma_lifcr_stream2.dma_clearisrflag_CTCIF, setBit dma_lifcr_stream2.dma_clearisrflag_CHTIF, setBit dma_lifcr_stream2.dma_clearisrflag_CTEIF, setBit dma_lifcr_stream2.dma_clearisrflag_CDMEIF, setBit dma_lifcr_stream2.dma_clearisrflag_CFEIF */
    ;
    
    uint32_t n_cse26 = (uint32_t) ((uint32_t) 1U << (uint32_t) 19U);
    
    ivory_hw_io_write_u32((uint32_t) 1073897480U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 1U << (uint32_t) 21U) | (uint32_t) ((uint32_t) 1U << (uint32_t) 20U)) | n_cse26) | (uint32_t) ((uint32_t) 1U << (uint32_t) 18U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 16U)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073897536U);
    
    /* reg modify dma1->s2cr: setField dma_sxcr_ct, setField dma_sxcr_en */
    ;
    
    bool n_cse45 = (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r3 >> (uint32_t) 19U) & (uint32_t) 1U) & (uint16_t) 255U));
    
    ivory_hw_io_write_u32((uint32_t) 1073897536U, (uint32_t) ((uint32_t) ((uint32_t) ~(uint32_t) ((uint32_t) 1U << 0) & (uint32_t) ((uint32_t) (n_r4 & (uint32_t) ~n_cse26) | (uint32_t) ((uint32_t) (uint8_t) ((bool) !n_cse45 ? (uint8_t) 1U : 0) << (uint32_t) 19U))) | (uint32_t) ((uint32_t) 1U << 0)));
    
    int32_t n_deref5 = uart4_dma_isr_buf.ivory_string_GPSString_len;
    
    if ((bool) (n_deref5 > (int32_t) 0)) {
        emitter_rx_flush_chan_150(&uart4_dma_isr_buf);
        uart4_dma_isr_buf.ivory_string_GPSString_len = (int32_t) 0;
    }
    
    uint16_t n_let6 = (uint16_t) (uint32_t) ((uint32_t) (n_r2 >> 0) & (uint32_t) 65535U);
    
    if ((bool) (n_let6 < (uint16_t) 127U)) {
        if (n_cse45) {
            uart4_dma_rx1_buf.ivory_string_GPSString_len = (int32_t) (uint16_t) ((uint16_t) 127U - n_let6);
            emitter_rx_flush_chan_150(&uart4_dma_rx1_buf);
        } else {
            uart4_dma_rx0_buf.ivory_string_GPSString_len = (int32_t) (uint16_t) ((uint16_t) 127U - n_let6);
            emitter_rx_flush_chan_150(&uart4_dma_rx0_buf);
        }
    }
}

void callback_write_gps_output_attr_thread_period_33ms(const struct position_sample *n_var0)
{
    emitter_write_gps_output_attr_chan_37(n_var0);
}

void callback_ublox_istream_thread_period_33ms(const uint8_t *n_var0)
{
    uint8_t n_deref0 = *n_var0;
    uint32_t n_deref1 = decodestate;
    
    if ((bool) ((bool) (0 == n_deref1) && (bool) (n_deref0 == (uint8_t) 181U))) {
        decodestate = (uint32_t) 1U;
    } else {
        if ((bool) ((bool) (n_deref1 == (uint32_t) 1U) && (bool) (n_deref0 == (uint8_t) 98U))) {
            decodestate = (uint32_t) 2U;
        } else {
            if ((bool) ((uint32_t) 2U == n_deref1)) {
                ck_a = (uint8_t) 0U;
                ck_b = (uint8_t) 0U;
                for (int32_t n_ix2 = (int32_t) 0; n_ix2 <= (int32_t) 51; n_ix2++) {
                    payload[n_ix2] = (uint8_t) 0U;
                }
                
                uint8_t n_deref3 = ck_a;
                uint8_t n_deref4 = ck_b;
                uint16_t n_cse14 = (uint16_t) n_deref3;
                uint16_t n_cse15 = (uint16_t) n_deref0;
                
                ck_a = (uint8_t) (uint16_t) ((uint16_t) (n_cse14 + n_cse15) & (uint16_t) 255U);
                ck_b = (uint8_t) (uint16_t) ((uint16_t) (n_cse15 + (uint16_t) (n_cse14 + (uint16_t) n_deref4)) & (uint16_t) 255U);
                pktClass = n_deref0;
                decodestate = (uint32_t) 3U;
            } else {
                if ((bool) (n_deref1 == (uint32_t) 3U)) {
                    uint8_t n_deref5 = ck_a;
                    uint8_t n_deref6 = ck_b;
                    uint16_t n_cse25 = (uint16_t) n_deref0;
                    uint16_t n_cse26 = (uint16_t) n_deref5;
                    
                    ck_a = (uint8_t) (uint16_t) ((uint16_t) (n_cse25 + n_cse26) & (uint16_t) 255U);
                    ck_b = (uint8_t) (uint16_t) ((uint16_t) (n_cse25 + (uint16_t) (n_cse26 + (uint16_t) n_deref6)) & (uint16_t) 255U);
                    pktId = n_deref0;
                    decodestate = (uint32_t) 4U;
                } else {
                    if ((bool) (n_deref1 == (uint32_t) 4U)) {
                        uint8_t n_deref7 = ck_a;
                        uint8_t n_deref8 = ck_b;
                        uint16_t n_cse36 = (uint16_t) n_deref0;
                        uint16_t n_cse37 = (uint16_t) n_deref7;
                        
                        ck_a = (uint8_t) (uint16_t) ((uint16_t) (n_cse36 + n_cse37) & (uint16_t) 255U);
                        ck_b = (uint8_t) (uint16_t) ((uint16_t) (n_cse36 + (uint16_t) (n_cse37 + (uint16_t) n_deref8)) & (uint16_t) 255U);
                        pktLen = n_cse36;
                        decodestate = (uint32_t) 5U;
                    } else {
                        if ((bool) (n_deref1 == (uint32_t) 5U)) {
                            uint8_t n_deref9 = ck_a;
                            uint8_t n_deref10 = ck_b;
                            uint16_t n_cse47 = (uint16_t) n_deref0;
                            uint16_t n_cse48 = (uint16_t) n_deref9;
                            
                            ck_a = (uint8_t) (uint16_t) ((uint16_t) (n_cse47 + n_cse48) & (uint16_t) 255U);
                            ck_b = (uint8_t) (uint16_t) ((uint16_t) (n_cse47 + (uint16_t) (n_cse48 + (uint16_t) n_deref10)) & (uint16_t) 255U);
                            
                            uint16_t n_deref11 = pktLen;
                            uint16_t n_cse58 = (uint16_t) ((uint16_t) (n_cse47 * (uint16_t) 256U) + n_deref11);
                            
                            if ((bool) (n_cse58 <= (uint16_t) 52U)) {
                                pktLen = n_cse58;
                                payOffs = (uint16_t) 0U;
                                decodestate = (uint32_t) 6U;
                            } else {
                                decodestate = (uint32_t) 0U;
                            }
                        } else {
                            if ((bool) (n_deref1 == (uint32_t) 6U)) {
                                uint16_t n_deref12 = payOffs;
                                uint16_t n_deref13 = pktLen;
                                
                                if ((bool) (n_deref12 < n_deref13)) {
                                    uint8_t n_deref14 = ck_a;
                                    uint8_t n_deref15 = ck_b;
                                    uint16_t n_cse62 = (uint16_t) n_deref0;
                                    uint16_t n_cse63 = (uint16_t) n_deref14;
                                    
                                    ck_a = (uint8_t) (uint16_t) ((uint16_t) (n_cse62 + n_cse63) & (uint16_t) 255U);
                                    ck_b = (uint8_t) (uint16_t) ((uint16_t) (n_cse62 + (uint16_t) (n_cse63 + (uint16_t) n_deref15)) & (uint16_t) 255U);
                                    if ((bool) (n_deref12 < (uint16_t) 52U)) {
                                        payload[(int32_t) n_deref12 % 52] = n_deref0;
                                    }
                                    payOffs = (uint16_t) ((uint16_t) 1U + n_deref12);
                                } else {
                                    uint8_t n_deref16 = ck_a;
                                    
                                    if ((bool) (n_deref0 == n_deref16)) {
                                        decodestate = (uint32_t) 7U;
                                    } else {
                                        decodestate = (uint32_t) 0U;
                                    }
                                }
                            } else {
                                if ((bool) (n_deref1 == (uint32_t) 7U)) {
                                    uint8_t n_deref17 = ck_b;
                                    
                                    if ((bool) (n_deref0 == n_deref17)) {
                                        uint8_t n_deref18 = pktClass;
                                        uint8_t n_deref19 = pktId;
                                        uint16_t n_deref20 = payOffs;
                                        
                                        ublox_decode(&decode_state, n_deref18, n_deref19, payload, n_deref20, &position_1);
                                        
                                        uint8_t n_deref21 = decode_state;
                                        
                                        if ((bool) (n_deref21 == (uint8_t) 7U)) {
                                            int64_t n_r22 = tower_get_time();
                                            
                                            position_1.time = n_r22;
                                            emitter_ublox_istream_chan_147(&position_1);
                                            decode_state = (uint8_t) 0U;
                                        }
                                    }
                                    decodestate = (uint32_t) 0U;
                                } else {
                                    decodestate = (uint32_t) 0U;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

void callback_uart4_buf_rx_thread_period_33ms(const struct ivory_string_GPSString *n_var0)
{
    int32_t n_deref0 = n_var0->ivory_string_GPSString_len;
    
    for (int32_t n_ix1 = (int32_t) 0; n_ix1 <= (int32_t) 127; n_ix1++) {
        if ((bool) (n_ix1 < n_deref0)) {
            emitter_uart4_buf_rx_chan_152(&n_var0->ivory_string_GPSString_data[n_ix1]);
        }
    }
}

void callback_gps_output_attr_update_thread_period_33ms(const struct position_sample *n_var0)
{
    gps_output_attr = *n_var0;
}

void emitter_rx_flush_chan_150(const struct ivory_string_GPSString *n_var0)
{
    emitter_rx_flush_chan_150_thread_period_33ms_emit(n_var0);
}

void emitter_write_gps_output_attr_chan_37(const struct position_sample *n_var0)
{
    emitter_write_gps_output_attr_chan_37_thread_period_33ms_emit(n_var0);
}

void emitter_ublox_istream_chan_147(const struct position_sample *n_var0)
{
    emitter_ublox_istream_chan_147_thread_period_33ms_emit(n_var0);
}

void emitter_uart4_buf_rx_chan_152(const uint8_t *n_var0)
{
    emitter_uart4_buf_rx_chan_152_thread_period_33ms_emit(n_var0);
}
