/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_user_input_request_attrServer.h"

struct mutex lock_user_input_request_attrServer;

void monitor_init_user_input_request_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_user_input_request_attrServer);
}

void monitor_lock_user_input_request_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_user_input_request_attrServer);
}

void monitor_unlock_user_input_request_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_user_input_request_attrServer);
}
