/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_nominal_throttle_attrServer.h"

struct mutex lock_nominal_throttle_attrServer;

void monitor_init_nominal_throttle_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_nominal_throttle_attrServer);
}

void monitor_lock_nominal_throttle_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_nominal_throttle_attrServer);
}

void monitor_unlock_nominal_throttle_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_nominal_throttle_attrServer);
}
