/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_DMA1_Stream4_IRQHandler.h"

void callback_tx_stream_interrupt_thread_signal_DMA1_Stream4_IRQHandler(const int64_t *n_var0)
{
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073897584U);
            
            /* reg modify dma1->s4cr: clearBit dma_sxcr_en */
            ;
            ivory_hw_io_write_u32((uint32_t) 1073897584U, (uint32_t) (n_r0 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)));
            /* reg get dma1->s4cr:  */
            ;
            
            uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073897584U);
            
            if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r1 >> 0) & (uint32_t) 1U) & (uint16_t) 255U))) {
                break;
            }
        }
    }
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073897584U);
    
    /* reg modify dma1->s4cr: setField dma_sxcr_tcie, setField dma_sxcr_teie, setField dma_sxcr_dmeie */
    ;
    
    uint32_t n_cse14 = (uint32_t) ((uint32_t) 1U << (uint32_t) 4U);
    uint32_t n_cse18 = (uint32_t) 0;
    uint32_t n_cse21 = (uint32_t) ((uint32_t) 1U << (uint32_t) 2U);
    
    ivory_hw_io_write_u32((uint32_t) 1073897584U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_r2 & (uint32_t) ~n_cse14) | (uint32_t) (n_cse18 << (uint32_t) 4U)) & (uint32_t) ~n_cse21) | (uint32_t) (n_cse18 << (uint32_t) 2U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) | (uint32_t) (n_cse18 << (uint32_t) 1U)));
    /* reg get dma1->hisr:  */
    ;
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073897476U);
    uint8_t n_cse37 = (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r3 >> 0) & (uint32_t) 63U) & (uint16_t) 255U);
    bool n_cse41 = (bool) (0 != (uint8_t) ((uint8_t) (n_cse37 >> (uint8_t) 5U) & (uint8_t) 1U));
    
    if (n_cse41) {
        uint32_t n_deref4 = uart4_dma_tx_complete;
        
        uart4_dma_tx_complete = (uint32_t) ((uint32_t) 1U + n_deref4);
    }
    if ((bool) (0 != (uint8_t) ((uint8_t) (n_cse37 >> (uint8_t) 3U) & (uint8_t) 1U))) {
        uint32_t n_deref5 = uart4_dma_tx_transfer_err;
        
        uart4_dma_tx_transfer_err = (uint32_t) ((uint32_t) 1U + n_deref5);
    }
    if ((bool) (0 != (uint8_t) ((uint8_t) (n_cse37 >> (uint8_t) 2U) & (uint8_t) 1U))) {
        uint32_t n_deref6 = uart4_dma_tx_direct_err;
        
        uart4_dma_tx_direct_err = (uint32_t) ((uint32_t) 1U + n_deref6);
    }
    /* reg set dma1->hifcr: setBit dma_hifcr_stream4.dma_clearisrflag_CTCIF, setBit dma_hifcr_stream4.dma_clearisrflag_CHTIF, setBit dma_hifcr_stream4.dma_clearisrflag_CTEIF, setBit dma_hifcr_stream4.dma_clearisrflag_CDMEIF, setBit dma_hifcr_stream4.dma_clearisrflag_CFEIF */
    ivory_hw_io_write_u32((uint32_t) 1073897484U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 1U << 0) | n_cse21) | n_cse14) | (uint32_t) ((uint32_t) 1U << (uint32_t) 5U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 3U)));
    
    bool n_local7 = n_cse41;
    bool *n_ref8 = &n_local7;
    
    uart4_dma_tx_active = false;
    /* reg set nvic_iser0: setBit nvic_iser_setena.[15] */
    ivory_hw_io_write_u32((uint32_t) 3758153984U, (uint32_t) ((uint32_t) 1U << (uint32_t) 15U));
}
