/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_uart4_dma_rx_byte_shim.h"

struct mutex lock_uart4_dma_rx_byte_shim;

void monitor_init_uart4_dma_rx_byte_shim(void)
{
    ivory_freertos_mutex_create(&lock_uart4_dma_rx_byte_shim);
}

void monitor_lock_uart4_dma_rx_byte_shim(void)
{
    ivory_freertos_mutex_takeblocking(&lock_uart4_dma_rx_byte_shim);
}

void monitor_unlock_uart4_dma_rx_byte_shim(void)
{
    ivory_freertos_mutex_give(&lock_uart4_dma_rx_byte_shim);
}
