/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_i2c2PeripheralDriver.h"

uint8_t i2c2_driverstate = (uint8_t) 0U;

bool i2c2_ready_sent;

struct i2c_transaction_request i2c2_reqbuffer;

int32_t i2c2_reqbufferpos;

struct i2c_transaction_result i2c2_resbuffer;

int32_t i2c2_resbufferpos;

uint32_t i2c2_invalid_request;

uint32_t i2c2_error_run;

int64_t i2c2_last_event;
