/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_l3gd20Ctl.h"

struct mutex lock_l3gd20Ctl;

void monitor_init_l3gd20Ctl(void)
{
    ivory_freertos_mutex_create(&lock_l3gd20Ctl);
}

void monitor_lock_l3gd20Ctl(void)
{
    ivory_freertos_mutex_takeblocking(&lock_l3gd20Ctl);
}

void monitor_unlock_l3gd20Ctl(void)
{
    ivory_freertos_mutex_give(&lock_l3gd20Ctl);
}
