/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_mpu6kCtl.h"

uint8_t retries;

bool ready;

bool transaction_pending;

struct gyroscope_sample gyro;

struct accelerometer_sample accel;

struct spi_transaction_result last_value_2;

struct mpu6000_continuation mpu6000_cont;
