/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_packed_status_attrServer.h"

struct mutex lock_packed_status_attrServer;

void monitor_init_packed_status_attrServer(void)
{
    ivory_freertos_mutex_create(&lock_packed_status_attrServer);
}

void monitor_lock_packed_status_attrServer(void)
{
    ivory_freertos_mutex_takeblocking(&lock_packed_status_attrServer);
}

void monitor_unlock_packed_status_attrServer(void)
{
    ivory_freertos_mutex_give(&lock_packed_status_attrServer);
}
