/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __STM32_MAIN_H__
#define __STM32_MAIN_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <ivory_hw_prim.h>
#include <stm32_freertos_init.h>
void Reset_Handler(void);

#ifdef __cplusplus
}
#endif
#endif /* __STM32_MAIN_H__ */
