/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_state_monitor_simplecontroller.h"

bool tx_pending;

struct can_message last_sent;

uint32_t can_received_count = (uint32_t) 0U;
