/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_signal_CAN1_RX0_IRQHandler.h"

static struct can_message emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_0;

static struct can_message emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_1;

static struct can_message emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_2;

static uint32_t emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_count;

struct binary_semaphore signal_semaphore_thread_signal_CAN1_RX0_IRQHandler;

static void handler_run_result_thread_signal_CAN1_RX0_IRQHandler(const struct can_message *n_var0);

static void handler_run_rx0_irq_thread_signal_CAN1_RX0_IRQHandler(const int64_t *n_var0);

void loop_thread_signal_CAN1_RX0_IRQHandler(struct taskarg *n_var0)
{
    uint32_t n_r0 = ivory_freertos_time_gettickrate_ms();
    
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            ivory_freertos_binary_semaphore_takeblocking(&signal_semaphore_thread_signal_CAN1_RX0_IRQHandler);
            
            uint32_t n_r1 = ivory_freertos_time_gettickcount();
            uint32_t n_cse3 = (uint32_t) (n_r1 / n_r0);
            int64_t n_local2 = (int64_t) ((int64_t) n_cse3 * (int64_t) 1000);
            int64_t *n_ref3 = &n_local2;
            
            handler_run_rx0_irq_thread_signal_CAN1_RX0_IRQHandler(n_ref3);
        }
    }
}

void CAN1_RX0_IRQHandler(void)
{
    /* reg set nvic_icer0: setBit nvic_icer_clrena.[20] */
    ivory_hw_io_write_u32((uint32_t) 3758154112U, (uint32_t) ((uint32_t) 1U << (uint32_t) 20U));
    ivory_freertos_binary_semaphore_give_from_isr(&signal_semaphore_thread_signal_CAN1_RX0_IRQHandler);
}

void emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_emit(const struct can_message *n_var0)
{
    uint32_t n_deref0 = emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_count;
    
    if ((bool) (n_deref0 <= (uint32_t) 2U)) {
        emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
        
        struct can_message *n_let1 = (struct can_message *) ((bool) ((uint32_t) 2U == n_deref0) ? &emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_2 : (struct can_message *) ((bool) (n_deref0 == (uint32_t) 1U) ? &emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_1 : &emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_0));
        
        *n_let1 = *n_var0;
    }
}

void handler_run_result_thread_signal_CAN1_RX0_IRQHandler(const struct can_message *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_simplecontroller();
    /* run callbacks */
    callback_result_thread_signal_CAN1_RX0_IRQHandler(n_var0);
    /* release monitor lock */
    monitor_unlock_simplecontroller();
    /* deliver emitters */
    ;
}

void handler_run_rx0_irq_thread_signal_CAN1_RX0_IRQHandler(const int64_t *n_var0)
{
    /* init emitters */
    emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_count = (uint32_t) 0U;
    /* take monitor lock */
    monitor_lock_can1PeripheralDriver();
    /* run callbacks */
    callback_rx0_irq_thread_signal_CAN1_RX0_IRQHandler(n_var0);
    /* release monitor lock */
    monitor_unlock_can1PeripheralDriver();
    /* deliver emitters */
    ;
    
    uint32_t n_deref0 = emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_count;
    
    if ((bool) (0 < n_deref0)) {
        handler_run_result_thread_signal_CAN1_RX0_IRQHandler(&emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_0);
    }
    if ((bool) ((uint32_t) 1U < n_deref0)) {
        handler_run_result_thread_signal_CAN1_RX0_IRQHandler(&emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_1);
    }
    if ((bool) ((uint32_t) 2U < n_deref0)) {
        handler_run_result_thread_signal_CAN1_RX0_IRQHandler(&emitter_rx0_irq_chan_1_thread_signal_CAN1_RX0_IRQHandler_message_2);
    }
}
