/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_SIMPLECONTROLLER_H__
#define __TOWER_STATE_MONITOR_SIMPLECONTROLLER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "canDriverTypes.h"
extern bool tx_pending;
extern struct can_message last_sent;
extern uint32_t can_received_count;

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_SIMPLECONTROLLER_H__ */
