/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_250ms.h"

static void emitter_periodic_chan_4(const bool *n_var0);

static void emitter_periodic_chan_2(const struct can_message *n_var0);

void callback_periodic_thread_period_250ms(const int64_t *n_var0)
{
    int64_t n_deref0 = *n_var0;
    uint64_t n_cse21 = (uint64_t) ((bool) (n_deref0 > (int64_t) 0) ? (uint64_t) n_deref0 : 0);
    struct can_message n_local1 = {.can_message_id =(uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 2047U << (uint32_t) 18U) & (uint32_t) 536870911U) << (uint32_t) 2U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)) | (uint32_t) ((uint32_t) 0 << 0)), .can_message_buf ={(uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 56U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 48U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 40U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 32U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 24U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 16U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 8U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> 0) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U)}, .can_message_len =
                                   (int32_t) 8};
    struct can_message *n_ref2 = &n_local1;
    
    last_sent = *n_ref2;
    
    bool n_deref3 = tx_pending;
    
    if (n_deref3) {
        bool n_local4 = true;
        bool *n_ref5 = &n_local4;
        
        emitter_periodic_chan_4(n_ref5);
    } else {
        emitter_periodic_chan_2(&last_sent);
        tx_pending = true;
    }
}

void callback_abort_thread_period_250ms(const bool *n_var0)
{
    /* reg set can1->tsr: setBit can_tsr_abrq0 */
    ivory_hw_io_write_u32((uint32_t) 1073767432U, (uint32_t) ((uint32_t) 1U << (uint32_t) 7U));
}

void callback_request_thread_period_250ms(const struct can_message *n_var0)
{
    /* reg get can1->tsr:  */
    ;
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073767432U);
    
    /* mailbox must be empty */
    ASSERTS((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> (uint32_t) 26U) & (uint32_t) 1U) & (uint16_t) 255U)));
    /* any completed request must have already been reported */
    ASSERTS((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r0 >> 0) & (uint32_t) 1U) & (uint16_t) 255U)));
    
    uint32_t n_deref1 = n_var0->can_message_id;
    int32_t n_deref2 = n_var0->can_message_len;
    const uint8_t *n_cse20 = n_var0->can_message_buf;
    uint8_t n_deref3 = n_cse20[(int32_t) 0];
    uint8_t n_deref4 = n_cse20[(int32_t) 1];
    uint8_t n_deref5 = n_cse20[(int32_t) 2];
    uint8_t n_deref6 = n_cse20[(int32_t) 3];
    uint8_t n_deref7 = n_cse20[(int32_t) 4];
    uint8_t n_deref8 = n_cse20[(int32_t) 5];
    uint8_t n_deref9 = n_cse20[(int32_t) 6];
    uint8_t n_deref10 = n_cse20[(int32_t) 7];
    uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073767812U);
    
    /* reg modify can1->tdt0r: clearBit can_tdtr_tgt, setField can_tdtr_dlc */
    ivory_hw_io_write_u32((uint32_t) 1073767812U, (uint32_t) ((uint32_t) ((uint32_t) (n_r11 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 8U)) & (uint32_t) ~(uint32_t) ((uint32_t) 15U << 0)) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) ((bool) ((bool) (n_deref2 <= (int32_t) UINT8_MAX) && (bool) (n_deref2 >= (int32_t) 0)) ? (uint8_t) n_deref2 : 0) & (uint8_t) 15U) << 0)));
    /* reg set can1->tdl0r: setField can_tdlr_data0, setField can_tdlr_data1, setField can_tdlr_data2, setField can_tdlr_data3 */
    ;
    
    uint32_t n_cse64 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 8U);
    uint32_t n_cse71 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 16U);
    uint32_t n_cse78 = (uint32_t) ~(uint32_t) ((uint32_t) 255U << (uint32_t) 24U);
    
    ivory_hw_io_write_u32((uint32_t) 1073767816U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) n_deref3 << 0) & n_cse64) | (uint32_t) ((uint32_t) n_deref4 << (uint32_t) 8U)) & n_cse71) | (uint32_t) ((uint32_t) n_deref5 << (uint32_t) 16U)) & n_cse78) | (uint32_t) ((uint32_t) n_deref6 << (uint32_t) 24U)));
    /* reg set can1->tdh0r: setField can_tdhr_data4, setField can_tdhr_data5, setField can_tdhr_data6, setField can_tdhr_data7 */
    ivory_hw_io_write_u32((uint32_t) 1073767820U, (uint32_t) ((uint32_t) (n_cse78 & (uint32_t) ((uint32_t) (n_cse71 & (uint32_t) ((uint32_t) (n_cse64 & (uint32_t) ((uint32_t) n_deref7 << 0)) | (uint32_t) ((uint32_t) n_deref8 << (uint32_t) 8U))) | (uint32_t) ((uint32_t) n_deref9 << (uint32_t) 16U))) | (uint32_t) ((uint32_t) n_deref10 << (uint32_t) 24U)));
    /* reg set can1->ti0r: setField can_tir_id, setField can_tir_ide, setField can_tir_rtr, setBit can_tir_txrq */
    ivory_hw_io_write_u32((uint32_t) 1073767808U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_deref1 >> (uint32_t) 2U) & (uint32_t) 536870911U) << (uint32_t) 3U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 2U)) | (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_deref1 >> (uint32_t) 1U) &
                                                                                                                                                                                                                                                                                                                                                         (uint32_t) 1U) & (uint16_t) 255U) << (uint32_t) 2U)) &
                                                                                      (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) | (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_deref1 >> 0) & (uint32_t) 1U) & (uint16_t) 255U) << (uint32_t) 1U)) | (uint32_t) ((uint32_t) 1U << 0)));
}

void emitter_periodic_chan_4(const bool *n_var0)
{
    emitter_periodic_chan_4_thread_period_250ms_emit(n_var0);
}

void emitter_periodic_chan_2(const struct can_message *n_var0)
{
    emitter_periodic_chan_2_thread_period_250ms_emit(n_var0);
}
