/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_MONITOR_CAN1PERIPHERALDRIVER_H__
#define __TOWER_GEN_MONITOR_CAN1PERIPHERALDRIVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "canDriverTypes.h"
#include <freertos_mutex_wrapper.h>
extern struct mutex lock_can1PeripheralDriver;
void monitor_init_can1PeripheralDriver(void);
void monitor_lock_can1PeripheralDriver(void);
void monitor_unlock_can1PeripheralDriver(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_MONITOR_CAN1PERIPHERALDRIVER_H__ */
