/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_CAN1_RX1_IRQHandler.h"

static void emitter_rx1_irq_chan_1(const struct can_message *n_var0);

void callback_result_thread_signal_CAN1_RX1_IRQHandler(const struct can_message *n_var0)
{
    uint32_t n_deref0 = can_received_count;
    
    can_received_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
    if ((bool) (0 == (uint32_t) (n_deref0 & (uint32_t) 1U))) {
        uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r1 & (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U)) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
    } else {
        uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
        
        /* reg modify gpioE->bsrr: setBit gpio_br_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r2 | (uint32_t) ((uint32_t) 1U << (uint32_t) 28U)));
        
        uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) ((uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U) & n_r3) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 1U << 0) << (uint32_t) 24U)));
    }
}

void callback_rx1_irq_thread_signal_CAN1_RX1_IRQHandler(const int64_t *n_var0)
{
    for (int32_t n_ix0 = (int32_t) 0; n_ix0 <= (int32_t) 2; n_ix0++) {
        /* reg get can1->rf1r:  */
        ;
        
        uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073767440U);
        
        if ((bool) ((uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r1 >> 0) & (uint32_t) 3U) & (uint16_t) 255U) == 0)) {
            break;
        }
        if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r1 >> (uint32_t) 5U) & (uint32_t) 1U) & (uint16_t) 255U))) {
            /* reg get can1->ri1r:  */
            ;
            
            uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073767872U);
            
            /* reg get can1->rdt1r:  */
            ;
            
            uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073767876U);
            
            /* reg get can1->rdl1r:  */
            ;
            
            uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073767880U);
            
            /* reg get can1->rdh1r:  */
            ;
            
            uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073767884U);
            
            /* reg set can1->rf1r: setBit can_rfr_rfom, setBit can_rfr_fovr, setBit can_rfr_full */
            ;
            ivory_hw_io_write_u32((uint32_t) 1073767440U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 1U << (uint32_t) 5U) | (uint32_t) ((uint32_t) 1U << (uint32_t) 4U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 3U)));
            
            struct can_message n_local6 = {.can_message_id =(uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_r2 >> (uint32_t) 3U) & (uint32_t) 536870911U) << (uint32_t) 2U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) | (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r2 >> (uint32_t) 2U) & (uint32_t) 1U) &
                                                                                                                                                                                                                                                                                                                            (uint16_t) 255U) << (uint32_t) 1U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)) |
                                                                        (uint32_t) ((uint32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r2 >> (uint32_t) 1U) & (uint32_t) 1U) & (uint16_t) 255U) << 0)), .can_message_buf ={(uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r4 >> 0) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r4 >> (uint32_t) 8U) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r4 >> (uint32_t) 16U) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r4 >> (uint32_t) 24U) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r5 >> 0) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r5 >> (uint32_t) 8U) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r5 >> (uint32_t) 16U) & (uint32_t) 255U) & (uint16_t) 255U),
                                                                                                                                                                                                                                              (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r5 >> (uint32_t) 24U) & (uint32_t) 255U) & (uint16_t) 255U)}, .can_message_len =
                                           (int32_t) (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (n_r3 >> 0) & (uint32_t) 15U) & (uint16_t) 255U) % 9};
            struct can_message *n_ref7 = &n_local6;
            
            emitter_rx1_irq_chan_1(n_ref7);
        }
    }
    /* reg set nvic_iser0: setBit nvic_iser_setena.[21] */
    ivory_hw_io_write_u32((uint32_t) 3758153984U, (uint32_t) ((uint32_t) 1U << (uint32_t) 21U));
}

void emitter_rx1_irq_chan_1(const struct can_message *n_var0)
{
    emitter_rx1_irq_chan_1_thread_signal_CAN1_RX1_IRQHandler_emit(n_var0);
}
