/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_INIT_H__
#define __TOWER_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_gen_monitor_can1PeripheralDriver.h"
#include "tower_gen_monitor_simplecontroller.h"
#include "tower_gen_thread_signal_CAN1_RX0_IRQHandler.h"
#include "tower_gen_thread_signal_CAN1_RX1_IRQHandler.h"
#include "tower_gen_thread_signal_CAN1_TX_IRQHandler.h"
#include "tower_gen_thread_period_250ms.h"
#include "tower_gen_thread_init.h"
#include <freertos_task_wrapper.h>
void tower_entry(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_INIT_H__ */
