/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "DMA1_Stream5_IRQHandler.h"

void DMA1_Stream5_IRQHandler(void)
{
    /* reg set nvic_icer0: setBit nvic_icer_clrena.[16] */
    ivory_hw_io_write_u32((uint32_t) 3758154112U, (uint32_t) ((uint32_t) 1U << (uint32_t) 16U));
    
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073897608U);
    
    /* reg modify dma1->s5cr: setField dma_sxcr_tcie, setField dma_sxcr_teie, setField dma_sxcr_dmeie */
    ;
    
    uint32_t n_cse8 = (uint32_t) 0;
    
    ivory_hw_io_write_u32((uint32_t) 1073897608U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_r0 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 4U)) | (uint32_t) (n_cse8 << (uint32_t) 4U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 2U)) | (uint32_t) (n_cse8 << (uint32_t) 2U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U)) |
                                                              (uint32_t) (n_cse8 << (uint32_t) 1U)));
}
