/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "echoprompt_monitor.h"

struct ivory_string_UARTBuffer out_req;

bool flush_defer;

bool initialized = false;

void callback_flush(const int64_t *n_var0)
{
    bool n_deref0 = initialized;
    
    if ((bool) !n_deref0) {
        initialized = true;
        
        const int32_t *n_cse0 = &out_req.ivory_string_UARTBuffer_len;
        int32_t n_deref1 = *n_cse0;
        
        if ((bool) (n_deref1 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref1 % 128] = (uint8_t) 13U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) (n_deref1 + (int32_t) 1);
        }
        
        int32_t n_deref2 = *n_cse0;
        
        if ((bool) (n_deref2 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref2 % 128] = (uint8_t) 10U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref2);
        }
        
        int32_t n_deref3 = *n_cse0;
        
        if ((bool) (n_deref3 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref3 % 128] = (uint8_t) 104U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref3);
        }
        
        int32_t n_deref4 = *n_cse0;
        
        if ((bool) (n_deref4 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref4 % 128] = (uint8_t) 101U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref4);
        }
        
        int32_t n_deref5 = *n_cse0;
        
        if ((bool) (n_deref5 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref5 % 128] = (uint8_t) 108U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref5);
        }
        
        int32_t n_deref6 = *n_cse0;
        
        if ((bool) (n_deref6 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref6 % 128] = (uint8_t) 108U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref6);
        }
        
        int32_t n_deref7 = *n_cse0;
        
        if ((bool) (n_deref7 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref7 % 128] = (uint8_t) 111U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref7);
        }
        
        int32_t n_deref8 = *n_cse0;
        
        if ((bool) (n_deref8 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref8 % 128] = (uint8_t) 32U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref8);
        }
        
        int32_t n_deref9 = *n_cse0;
        
        if ((bool) (n_deref9 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref9 % 128] = (uint8_t) 119U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref9);
        }
        
        int32_t n_deref10 = *n_cse0;
        
        if ((bool) (n_deref10 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref10 % 128] = (uint8_t) 111U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref10);
        }
        
        int32_t n_deref11 = *n_cse0;
        
        if ((bool) (n_deref11 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref11 % 128] = (uint8_t) 114U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref11);
        }
        
        int32_t n_deref12 = *n_cse0;
        
        if ((bool) (n_deref12 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref12 % 128] = (uint8_t) 108U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref12);
        }
        
        int32_t n_deref13 = *n_cse0;
        
        if ((bool) (n_deref13 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref13 % 128] = (uint8_t) 100U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref13);
        }
        
        int32_t n_deref14 = *n_cse0;
        
        if ((bool) (n_deref14 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref14 % 128] = (uint8_t) 33U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref14);
        }
        
        int32_t n_deref15 = *n_cse0;
        
        if ((bool) (n_deref15 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref15 % 128] = (uint8_t) 13U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref15);
        }
        
        int32_t n_deref16 = *n_cse0;
        
        if ((bool) (n_deref16 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref16 % 128] = (uint8_t) 10U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref16);
        }
        
        int32_t n_deref17 = *n_cse0;
        
        if ((bool) (n_deref17 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref17 % 128] = (uint8_t) 13U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref17);
        }
        
        int32_t n_deref18 = *n_cse0;
        
        if ((bool) (n_deref18 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref18 % 128] = (uint8_t) 10U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref18);
        }
        
        int32_t n_deref19 = *n_cse0;
        
        if ((bool) (n_deref19 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref19 % 128] = (uint8_t) 116U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref19);
        }
        
        int32_t n_deref20 = *n_cse0;
        
        if ((bool) (n_deref20 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref20 % 128] = (uint8_t) 111U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref20);
        }
        
        int32_t n_deref21 = *n_cse0;
        
        if ((bool) (n_deref21 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref21 % 128] = (uint8_t) 119U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref21);
        }
        
        int32_t n_deref22 = *n_cse0;
        
        if ((bool) (n_deref22 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref22 % 128] = (uint8_t) 101U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref22);
        }
        
        int32_t n_deref23 = *n_cse0;
        
        if ((bool) (n_deref23 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref23 % 128] = (uint8_t) 114U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref23);
        }
        
        int32_t n_deref24 = *n_cse0;
        
        if ((bool) (n_deref24 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref24 % 128] = (uint8_t) 62U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref24);
        }
        
        int32_t n_deref25 = *n_cse0;
        
        if ((bool) (n_deref25 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref25 % 128] = (uint8_t) 32U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref25);
        }
    }
    
    const int32_t *n_cse151 = &out_req.ivory_string_UARTBuffer_len;
    int32_t n_deref26 = *n_cse151;
    
    if ((bool) (n_deref26 > (int32_t) 0)) {
        bool n_deref27 = flush_defer;
        int32_t n_deref28 = *n_cse151;
        
        if ((bool) ((bool) (n_deref28 > (int32_t) 0) && (bool) !n_deref27)) {
            emitter_flush_chan_3(&out_req);
            out_req.ivory_string_UARTBuffer_len = (int32_t) 0;
            flush_defer = true;
        }
    }
}

void callback_ostream(const uint8_t *n_var0)
{
    uint8_t n_deref0 = *n_var0;
    
    if ((bool) ((bool) (n_deref0 == (uint8_t) 10U) || (bool) (n_deref0 == (uint8_t) 13U))) {
        const int32_t *n_cse3 = &out_req.ivory_string_UARTBuffer_len;
        int32_t n_deref1 = *n_cse3;
        
        if ((bool) (n_deref1 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref1 % 128] = (uint8_t) 13U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) (n_deref1 + (int32_t) 1);
        }
        
        int32_t n_deref2 = *n_cse3;
        
        if ((bool) (n_deref2 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref2 % 128] = (uint8_t) 10U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref2);
        }
        
        int32_t n_deref3 = *n_cse3;
        
        if ((bool) (n_deref3 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref3 % 128] = (uint8_t) 13U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref3);
        }
        
        int32_t n_deref4 = *n_cse3;
        
        if ((bool) (n_deref4 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref4 % 128] = (uint8_t) 10U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref4);
        }
        
        int32_t n_deref5 = *n_cse3;
        
        if ((bool) (n_deref5 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref5 % 128] = (uint8_t) 116U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref5);
        }
        
        int32_t n_deref6 = *n_cse3;
        
        if ((bool) (n_deref6 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref6 % 128] = (uint8_t) 111U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref6);
        }
        
        int32_t n_deref7 = *n_cse3;
        
        if ((bool) (n_deref7 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref7 % 128] = (uint8_t) 119U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref7);
        }
        
        int32_t n_deref8 = *n_cse3;
        
        if ((bool) (n_deref8 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref8 % 128] = (uint8_t) 101U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref8);
        }
        
        int32_t n_deref9 = *n_cse3;
        
        if ((bool) (n_deref9 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref9 % 128] = (uint8_t) 114U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref9);
        }
        
        int32_t n_deref10 = *n_cse3;
        
        if ((bool) (n_deref10 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref10 % 128] = (uint8_t) 62U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref10);
        }
        
        int32_t n_deref11 = *n_cse3;
        
        if ((bool) (n_deref11 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref11 % 128] = (uint8_t) 32U;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref11);
        }
    } else {
        int32_t n_deref12 = out_req.ivory_string_UARTBuffer_len;
        
        if ((bool) (n_deref12 < (int32_t) 128)) {
            out_req.ivory_string_UARTBuffer_data[n_deref12 % 128] = n_deref0;
            out_req.ivory_string_UARTBuffer_len = (int32_t) ((int32_t) 1 + n_deref12);
        }
    }
    if ((bool) (n_deref0 == (uint8_t) 49U)) {
        bool n_local13 = true;
        bool *n_ref14 = &n_local13;
        
        emitter_ostream_chan_2(n_ref14);
    } else {
        if ((bool) (n_deref0 == (uint8_t) 50U)) {
            bool n_local15 = false;
            bool *n_ref16 = &n_local15;
            
            emitter_ostream_chan_2(n_ref16);
        }
    }
    
    bool n_deref17 = flush_defer;
    int32_t n_deref18 = out_req.ivory_string_UARTBuffer_len;
    
    if ((bool) ((bool) (n_deref18 > (int32_t) 0) && (bool) !n_deref17)) {
        emitter_ostream_chan_3(&out_req);
        out_req.ivory_string_UARTBuffer_len = (int32_t) 0;
        flush_defer = true;
    }
}

void callback_result(const bool *n_var0)
{
    flush_defer = false;
}
