/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __BLINKER_MONITOR_H__
#define __BLINKER_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_blinker.h>
void callback_per(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __BLINKER_MONITOR_H__ */
