/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __CALLBACK_10MS_H__
#define __CALLBACK_10MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <smaccm_thread_period_10ms.h>
void callback_10ms(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __CALLBACK_10MS_H__ */
