/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __DMA_MONITOR_H__
#define __DMA_MONITOR_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "uartTestTypes.h"
#include "towerDeps.h"
#include "main.h"
#include "tower_time.h"
#include <smaccm_dma.h>
#include <ivory_hw_prim.h>
extern uint32_t uart2_rx_overruns;
extern uint32_t uart2_rx_success;
extern struct ivory_string_UARTBuffer req_buf;
extern int32_t req_pos;
void callback_init(const int64_t *n_var0);
void callback_req_chan(const struct ivory_string_UARTBuffer *n_var0);
void callback_interrupt(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __DMA_MONITOR_H__ */
