/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __MAIN_H__
#define __MAIN_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include <ivory_hw_prim.h>
#include <debug.h>
#include <smaccm_decls.h>
#include <rtos-kochab.h>
#include <clock_driver.h>
void init_clocks(void);
void fatal(uint8_t n_var0);
void main(void);

#ifdef __cplusplus
}
#endif
#endif /* __MAIN_H__ */
