/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_signal_USART2_IRQHandler.h"

static bool emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_0;

static uint32_t emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_count;

struct binary_semaphore signal_semaphore_thread_signal_USART2_IRQHandler;

static void handler_run_result_thread_signal_USART2_IRQHandler(const bool *n_var0);

static void handler_run_interrupt_thread_signal_USART2_IRQHandler(const int64_t *n_var0);

void loop_thread_signal_USART2_IRQHandler(struct taskarg *n_var0)
{
    uint32_t n_r0 = ivory_freertos_time_gettickrate_ms();
    
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            ivory_freertos_binary_semaphore_takeblocking(&signal_semaphore_thread_signal_USART2_IRQHandler);
            
            uint32_t n_r1 = ivory_freertos_time_gettickcount();
            uint32_t n_cse3 = (uint32_t) (n_r1 / n_r0);
            int64_t n_local2 = (int64_t) ((int64_t) n_cse3 * (int64_t) 1000);
            int64_t *n_ref3 = &n_local2;
            
            handler_run_interrupt_thread_signal_USART2_IRQHandler(n_ref3);
        }
    }
}

void USART2_IRQHandler(void)
{
    /* reg set nvic_icer1: setBit nvic_icer_clrena.[6] */
    ivory_hw_io_write_u32((uint32_t) 3758154116U, (uint32_t) ((uint32_t) 1U << (uint32_t) 6U));
    ivory_freertos_binary_semaphore_give_from_isr(&signal_semaphore_thread_signal_USART2_IRQHandler);
}

void emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_emit(const bool *n_var0)
{
    uint32_t n_deref0 = emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_count;
    
    if ((bool) (n_deref0 <= 0)) {
        emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
        emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_0 = *n_var0;
    }
}

void handler_run_result_thread_signal_USART2_IRQHandler(const bool *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_randReporter();
    /* run callbacks */
    /* release monitor lock */
    monitor_unlock_randReporter();
    /* deliver emitters */
    ;
}

void handler_run_interrupt_thread_signal_USART2_IRQHandler(const int64_t *n_var0)
{
    /* init emitters */
    emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_count = (uint32_t) 0U;
    /* take monitor lock */
    monitor_lock_dma();
    /* run callbacks */
    callback_interrupt_thread_signal_USART2_IRQHandler(n_var0);
    /* release monitor lock */
    monitor_unlock_dma();
    /* deliver emitters */
    ;
    
    uint32_t n_deref0 = emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_count;
    
    if ((bool) (0 < n_deref0)) {
        handler_run_result_thread_signal_USART2_IRQHandler(&emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_message_0);
    }
}
