/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_signal_USART2_IRQHandler.h"

static void emitter_interrupt_chan_3(const bool *n_var0);

void callback_interrupt_thread_signal_USART2_IRQHandler(const int64_t *n_var0)
{
    /* reg get uart2->sr:  */
    ;
    
    uint16_t n_r0 = ivory_hw_io_read_u16((uint32_t) 1073759232U);
    
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r0 >> (uint16_t) 3U) & (uint16_t) 1U))) {
        /* reg get uart2->dr:  */
        ;
        
        uint16_t n_r1 = ivory_hw_io_read_u16((uint32_t) 1073759236U);
        uint8_t n_local2 = (uint8_t) (uint16_t) ((uint16_t) (n_r1 >> 0) & (uint16_t) 255U);
        uint8_t *n_ref3 = &n_local2;
        uint32_t n_deref4 = uart2_rx_overruns;
        
        uart2_rx_overruns = (uint32_t) ((uint32_t) 1U + n_deref4);
    }
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r0 >> (uint16_t) 5U) & (uint16_t) 1U))) {
        /* reg get uart2->dr:  */
        ;
        
        uint16_t n_r5 = ivory_hw_io_read_u16((uint32_t) 1073759236U);
        uint8_t n_local6 = (uint8_t) (uint16_t) ((uint16_t) (n_r5 >> 0) & (uint16_t) 255U);
        uint8_t *n_ref7 = &n_local6;
        uint32_t n_deref8 = uart2_rx_success;
        
        uart2_rx_success = (uint32_t) ((uint32_t) 1U + n_deref8);
    }
    if ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r0 >> (uint16_t) 7U) & (uint16_t) 1U))) {
        uint8_t n_local9 = (uint8_t) 0U;
        uint8_t *n_ref10 = &n_local9;
        bool n_local11 = false;
        bool *n_ref12 = &n_local11;
        int32_t n_deref13 = req_pos;
        const int32_t *n_cse31 = &req_buf.ivory_string_UARTBuffer_len;
        int32_t n_deref14 = *n_cse31;
        uint8_t *n_let15 = req_buf.ivory_string_UARTBuffer_data;
        
        if ((bool) (n_deref13 < n_deref14)) {
            uint8_t n_deref16 = n_let15[n_deref13 % 128];
            
            *n_ref10 = n_deref16;
            req_pos = (int32_t) ((int32_t) 1 + n_deref13);
            *n_ref12 = true;
        }
        
        bool n_deref17 = *n_ref12;
        
        if (n_deref17) {
            uint8_t n_deref18 = *n_ref10;
            
            /* reg set uart2->dr: setField uart_dr_data */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073759236U, (uint16_t) ((uint16_t) n_deref18 << 0));
        } else {
            int32_t n_deref19 = *n_cse31;
            bool n_let20 = (bool) (n_deref19 > (int32_t) 0);
            
            if (n_let20) {
                bool n_local21 = true;
                bool *n_ref22 = &n_local21;
                
                emitter_interrupt_chan_3(n_ref22);
            }
            req_buf.ivory_string_UARTBuffer_len = (int32_t) 0;
            
            uint16_t n_r23 = ivory_hw_io_read_u16((uint32_t) 1073759244U);
            
            /* reg modify uart2->cr1: setField uart_cr1_txeie */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073759244U, (uint16_t) ((uint16_t) (n_r23 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) | (uint16_t) ((uint16_t) 0 << (uint16_t) 7U)));
        }
    }
    /* reg set nvic_iser1: setBit nvic_iser_setena.[6] */
    ivory_hw_io_write_u32((uint32_t) 3758153988U, (uint32_t) ((uint32_t) 1U << (uint32_t) 6U));
}

void emitter_interrupt_chan_3(const bool *n_var0)
{
    emitter_interrupt_chan_3_thread_signal_USART2_IRQHandler_emit(n_var0);
}
