/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_THREAD_PERIOD_5MS_H__
#define __TOWER_GEN_THREAD_PERIOD_5MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "rngTestTypes.h"
#include "tower_user_thread_period_5ms.h"
#include "tower_gen_monitor_rngPeripheral.h"
#include "tower_gen_monitor_randReporter.h"
#include "tower_gen_monitor_dma.h"
#include <freertos_task_wrapper.h>
#include <freertos_time_wrapper.h>
void loop_thread_period_5ms(struct taskarg *n_var0);
void emitter_rands_chan_2_thread_period_5ms_emit(const struct ivory_string_UARTBuffer *n_var0);
void emitter_rngPoll_chan_5_thread_period_5ms_emit(const uint32_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_THREAD_PERIOD_5MS_H__ */
