/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_randReporter.h"

struct mutex lock_randReporter;

void monitor_init_randReporter(void)
{
    ivory_freertos_mutex_create(&lock_randReporter);
}

void monitor_lock_randReporter(void)
{
    ivory_freertos_mutex_takeblocking(&lock_randReporter);
}

void monitor_unlock_randReporter(void)
{
    ivory_freertos_mutex_give(&lock_randReporter);
}
