/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_RANDREPORTER_H__
#define __TOWER_STATE_MONITOR_RANDREPORTER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "rngTestTypes.h"
extern struct ivory_string_UARTBuffer out_req;
extern bool initialized;

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_RANDREPORTER_H__ */
