/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_init.h"

static void handler_run_i2c1_init_thread_init(const int64_t *n_var0);

void loop_thread_init(void)
{
    int64_t n_local0 = (int64_t) 0;
    int64_t *n_ref1 = &n_local0;
    bool n_cse1 = (bool) ((uint8_t) 12U < (uint8_t) ((uint8_t) 1U << (uint8_t) 4U));
    
    ASSERTS(n_cse1);
    
    uint8_t n_cse2 = (uint8_t) ((uint8_t) 12U << (uint8_t) 4U);
    
    ivory_hw_io_write_u8((uint32_t) 3758154783U, n_cse2);
    ASSERTS(n_cse1);
    ivory_hw_io_write_u8((uint32_t) 3758154784U, n_cse2);
    handler_run_i2c1_init_thread_init(n_ref1);
    return;
}

void handler_run_i2c1_init_thread_init(const int64_t *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_i2c1PeripheralDriver();
    /* run callbacks */
    callback_i2c1_init_thread_init(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c1PeripheralDriver();
    /* deliver emitters */
    ;
}
