/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_250ms.h"

static void emitter_periodic_chan_1(const struct i2c_transaction_request *n_var0);

static void emitter_i2c1_request_chan_2(const struct i2c_transaction_result *n_var0);

void callback_result_thread_period_250ms(const struct i2c_transaction_result *n_var0)
{ }

void callback_periodic_thread_period_250ms(const int64_t *n_var0)
{
    int64_t n_deref0 = *n_var0;
    int64_t n_cse0 = (int64_t) (n_deref0 % (int64_t) 500000);
    
    if ((bool) ((int64_t) ((bool) (n_cse0 < (int64_t) 0) ? (int64_t) (n_cse0 + (int64_t) 500000) : n_cse0) >= (int64_t) 250000)) {
        struct i2c_transaction_request n_local1 = {.tx_addr =(uint8_t) 80U, .tx_buf ={(uint8_t) 0U, (uint8_t) 242U, (uint8_t) 243U, (uint8_t) 238U}, .tx_len =(int32_t) 4, .rx_len =(int32_t) 0};
        struct i2c_transaction_request *n_ref2 = &n_local1;
        
        emitter_periodic_chan_1(n_ref2);
    } else {
        struct i2c_transaction_request n_local3 = {.tx_addr =(uint8_t) 80U, .tx_buf ={(uint8_t) 0U}, .tx_len =(int32_t) 1, .rx_len =(int32_t) 3};
        struct i2c_transaction_request *n_ref4 = &n_local3;
        
        emitter_periodic_chan_1(n_ref4);
    }
}

void callback_i2c1_request_thread_period_250ms(const struct i2c_transaction_request *n_var0)
{
    bool n_deref0 = i2c1_ready_sent;
    uint8_t n_deref1 = i2c1_driverstate;
    
    if ((bool) (n_deref0 && (bool) (0 == n_deref1))) {
        /* reg get i2c1->cr1:  */
        ;
        
        uint16_t n_r2 = ivory_hw_io_read_u16((uint32_t) 1073763328U);
        
        if ((bool) ((bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 8U) & (uint16_t) 1U)) || (bool) (0 != (uint8_t) (uint16_t) ((uint16_t) (n_r2 >> (uint16_t) 9U) & (uint16_t) 1U)))) {
            uint32_t n_deref3 = i2c1_error_run;
            
            i2c1_error_run = (uint32_t) ((uint32_t) 1U + n_deref3);
            
            uint16_t n_r4 = ivory_hw_io_read_u16((uint32_t) 1073763348U);
            
            /* reg modify i2c1->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
            ;
            
            uint16_t n_cse31 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
            uint16_t n_cse34 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
            uint16_t n_cse37 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
            
            ivory_hw_io_write_u16((uint32_t) 1073763348U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) (n_r4 & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                         (uint16_t) 12U)) &
                                                                                                                                                                                              (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & n_cse31) & n_cse34) & n_cse37) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) &
                                                                                                                      (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << 0)));
            
            uint16_t n_r5 = ivory_hw_io_read_u16((uint32_t) 1073763332U);
            
            /* reg modify i2c1->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073763332U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse37 & n_cse34) & n_cse31) & n_r5));
            
            uint8_t n_deref6 = i2c1_driverstate;
            
            i2c1_driverstate = (uint8_t) 0U;
            i2c1_resbuffer.resultcode = (uint8_t) 1U;
            
            uint32_t n_deref7 = i2c1_error_run;
            
            i2c1_error_run = (uint32_t) ((uint32_t) 1U + n_deref7);
            emitter_i2c1_request_chan_2(&i2c1_resbuffer);
        } else {
            /* reg set i2c1->cr1: setBit i2c_cr1_pe */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073763328U, (uint16_t) ((uint16_t) 1U << 0));
            i2c1_driverstate = (uint8_t) 1U;
            i2c1_reqbuffer = *n_var0;
            i2c1_reqbufferpos = (int32_t) 0;
            i2c1_resbufferpos = (int32_t) 0;
            
            int64_t n_r8 = tower_get_time();
            
            i2c1_last_event = n_r8;
            
            uint16_t n_r9 = ivory_hw_io_read_u16((uint32_t) 1073763332U);
            
            /* reg modify i2c1->cr2: setBit i2c_cr2_itbufen, setBit i2c_cr2_itevten, setBit i2c_cr2_iterren */
            ;
            
            uint16_t n_cse73 = (uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
            
            ivory_hw_io_write_u16((uint32_t) 1073763332U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse73 | (uint16_t) ((uint16_t) 1U << (uint16_t) 9U)) | (uint16_t) ((uint16_t) 1U << (uint16_t) 10U)) | n_r9));
            
            uint16_t n_r10 = ivory_hw_io_read_u16((uint32_t) 1073763328U);
            
            /* reg modify i2c1->cr1: setBit i2c_cr1_start */
            ;
            ivory_hw_io_write_u16((uint32_t) 1073763328U, (uint16_t) (n_cse73 | n_r10));
            for (int32_t n_ix11 = (int32_t) 14; n_ix11 >= (int32_t) 0; n_ix11--) {
                /* reg get i2c1->cr1:  */
                ;
                
                uint16_t n_r12 = ivory_hw_io_read_u16((uint32_t) 1073763328U);
                
                if ((bool) (0 == (uint8_t) (uint16_t) ((uint16_t) (n_r12 >> (uint16_t) 8U) & (uint16_t) 1U))) {
                    break;
                }
            }
        }
    } else {
        uint32_t n_deref13 = i2c1_invalid_request;
        
        i2c1_invalid_request = (uint32_t) ((uint32_t) 1U + n_deref13);
        
        uint16_t n_r14 = ivory_hw_io_read_u16((uint32_t) 1073763348U);
        
        /* reg modify i2c1->sr1: clearBit i2c_sr1_smbalert, clearBit i2c_sr1_timeout, clearBit i2c_sr1_pecerr, clearBit i2c_sr1_ovr, clearBit i2c_sr1_af, clearBit i2c_sr1_arlo, clearBit i2c_sr1_berr, clearBit i2c_sr1_txe, clearBit i2c_sr1_rxne, clearBit i2c_sr1_stopf, clearBit i2c_sr1_add10, clearBit i2c_sr1_btf, clearBit i2c_sr1_addr, clearBit i2c_sr1_sb */
        ;
        
        uint16_t n_cse112 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 8U);
        uint16_t n_cse114 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 9U);
        uint16_t n_cse116 = (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 10U);
        
        ivory_hw_io_write_u16((uint32_t) 1073763348U, (uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ((uint16_t) ~(uint16_t) ((uint16_t) 1U << 0) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 1U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 2U)) &
                                                                                                                                                                                                      (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 3U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 4U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 6U)) &
                                                                                                                                                                  (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 7U)) & n_cse112) & n_cse114) & n_cse116) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 11U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 12U)) &
                                                                                          (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 14U)) & (uint16_t) ~(uint16_t) ((uint16_t) 1U << (uint16_t) 15U)) & n_r14));
        
        uint16_t n_r15 = ivory_hw_io_read_u16((uint32_t) 1073763332U);
        
        /* reg modify i2c1->cr2: clearBit i2c_cr2_itbufen, clearBit i2c_cr2_itevten, clearBit i2c_cr2_iterren */
        ;
        ivory_hw_io_write_u16((uint32_t) 1073763332U, (uint16_t) ((uint16_t) ((uint16_t) (n_cse112 & n_cse114) & n_cse116) & n_r15));
        
        uint8_t n_deref16 = i2c1_driverstate;
        
        i2c1_driverstate = (uint8_t) 0U;
        i2c1_resbuffer.resultcode = (uint8_t) 1U;
        
        uint32_t n_deref17 = i2c1_error_run;
        
        i2c1_error_run = (uint32_t) ((uint32_t) 1U + n_deref17);
        emitter_i2c1_request_chan_2(&i2c1_resbuffer);
    }
}

void emitter_periodic_chan_1(const struct i2c_transaction_request *n_var0)
{
    emitter_periodic_chan_1_thread_period_250ms_emit(n_var0);
}

void emitter_i2c1_request_chan_2(const struct i2c_transaction_result *n_var0)
{
    emitter_i2c1_request_chan_2_thread_period_250ms_emit(n_var0);
}
