/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_MONITOR_I2C1PERIPHERALDRIVER_H__
#define __TOWER_GEN_MONITOR_I2C1PERIPHERALDRIVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2cTowerTypes.h"
#include <freertos_mutex_wrapper.h>
extern struct mutex lock_i2c1PeripheralDriver;
void monitor_init_i2c1PeripheralDriver(void);
void monitor_lock_i2c1PeripheralDriver(void);
void monitor_unlock_i2c1PeripheralDriver(void);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_MONITOR_I2C1PERIPHERALDRIVER_H__ */
