/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_thread_period_250ms.h"

static struct i2c_transaction_request emitter_periodic_chan_1_thread_period_250ms_message_0;

static uint32_t emitter_periodic_chan_1_thread_period_250ms_message_count;

static struct i2c_transaction_result emitter_i2c1_request_chan_2_thread_period_250ms_message_0;

static uint32_t emitter_i2c1_request_chan_2_thread_period_250ms_message_count;

static void handler_run_result_thread_period_250ms(const struct i2c_transaction_result *n_var0);

static void handler_run_periodic_thread_period_250ms(const int64_t *n_var0);

static void handler_run_i2c1_request_thread_period_250ms(const struct i2c_transaction_request *n_var0);

void loop_thread_period_250ms(struct taskarg *n_var0)
{
    uint32_t n_r0 = ivory_freertos_time_gettickrate_ms();
    uint32_t n_r1 = ivory_freertos_time_gettickcount();
    uint32_t n_local2 = n_r1;
    uint32_t *n_ref3 = &n_local2;
    
    {
        int forever_loop __attribute__((unused));
        
        for (forever_loop = 0; IFOREVER; IFOREVER_INC) {
            ivory_freertos_time_delayuntil(n_ref3, (uint32_t) (n_r0 * (uint32_t) 250U));
            
            uint32_t n_deref4 = *n_ref3;
            uint32_t n_cse13 = (uint32_t) (n_deref4 / n_r0);
            int64_t n_local5 = (int64_t) ((int64_t) n_cse13 * (int64_t) 1000);
            int64_t *n_ref6 = &n_local5;
            
            handler_run_periodic_thread_period_250ms(n_ref6);
        }
    }
}

void emitter_periodic_chan_1_thread_period_250ms_emit(const struct i2c_transaction_request *n_var0)
{
    uint32_t n_deref0 = emitter_periodic_chan_1_thread_period_250ms_message_count;
    
    if ((bool) (n_deref0 <= 0)) {
        emitter_periodic_chan_1_thread_period_250ms_message_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
        emitter_periodic_chan_1_thread_period_250ms_message_0 = *n_var0;
    }
}

void emitter_i2c1_request_chan_2_thread_period_250ms_emit(const struct i2c_transaction_result *n_var0)
{
    uint32_t n_deref0 = emitter_i2c1_request_chan_2_thread_period_250ms_message_count;
    
    if ((bool) (n_deref0 <= 0)) {
        emitter_i2c1_request_chan_2_thread_period_250ms_message_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
        emitter_i2c1_request_chan_2_thread_period_250ms_message_0 = *n_var0;
    }
}

void handler_run_result_thread_period_250ms(const struct i2c_transaction_result *n_var0)
{
    /* init emitters */
    /* take monitor lock */
    monitor_lock_simplecontroller();
    /* run callbacks */
    callback_result_thread_period_250ms(n_var0);
    /* release monitor lock */
    monitor_unlock_simplecontroller();
    /* deliver emitters */
    ;
}

void handler_run_periodic_thread_period_250ms(const int64_t *n_var0)
{
    /* init emitters */
    emitter_periodic_chan_1_thread_period_250ms_message_count = (uint32_t) 0U;
    /* take monitor lock */
    monitor_lock_simplecontroller();
    /* run callbacks */
    callback_periodic_thread_period_250ms(n_var0);
    /* release monitor lock */
    monitor_unlock_simplecontroller();
    /* deliver emitters */
    ;
    
    uint32_t n_deref0 = emitter_periodic_chan_1_thread_period_250ms_message_count;
    
    if ((bool) (0 < n_deref0)) {
        handler_run_i2c1_request_thread_period_250ms(&emitter_periodic_chan_1_thread_period_250ms_message_0);
    }
}

void handler_run_i2c1_request_thread_period_250ms(const struct i2c_transaction_request *n_var0)
{
    /* init emitters */
    emitter_i2c1_request_chan_2_thread_period_250ms_message_count = (uint32_t) 0U;
    /* take monitor lock */
    monitor_lock_i2c1PeripheralDriver();
    /* run callbacks */
    callback_i2c1_request_thread_period_250ms(n_var0);
    /* release monitor lock */
    monitor_unlock_i2c1PeripheralDriver();
    /* deliver emitters */
    ;
    
    uint32_t n_deref0 = emitter_i2c1_request_chan_2_thread_period_250ms_message_count;
    
    if ((bool) (0 < n_deref0)) {
        handler_run_result_thread_period_250ms(&emitter_i2c1_request_chan_2_thread_period_250ms_message_0);
    }
}
