/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_USER_THREAD_PERIOD_1MS_H__
#define __TOWER_USER_THREAD_PERIOD_1MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2cTowerTypes.h"
#include "tower_state_monitor_i2c1PeripheralDriver.h"
#include "tower_gen_thread_period_1ms.h"
#include "tower_time.h"
void callback_i2c1_ready_period_thread_period_1ms(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_USER_THREAD_PERIOD_1MS_H__ */
