/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_STATE_MONITOR_I2C1PERIPHERALDRIVER_H__
#define __TOWER_STATE_MONITOR_I2C1PERIPHERALDRIVER_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "i2cTowerTypes.h"
#include <ivory_hw_prim.h>
extern uint8_t i2c1_driverstate;
extern bool i2c1_ready_sent;
extern struct i2c_transaction_request i2c1_reqbuffer;
extern int32_t i2c1_reqbufferpos;
extern struct i2c_transaction_result i2c1_resbuffer;
extern int32_t i2c1_resbufferpos;
extern uint32_t i2c1_invalid_request;
extern uint32_t i2c1_error_run;
extern int64_t i2c1_last_event;

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_STATE_MONITOR_I2C1PERIPHERALDRIVER_H__ */
