/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_init.h"

void tower_entry(void)
{
    monitor_init_i2c1PeripheralDriver();
    monitor_init_simplecontroller();
    ivory_freertos_binary_semaphore_create(&signal_semaphore_thread_signal_I2C1_ER_IRQHandler);
    ivory_freertos_binary_semaphore_create(&signal_semaphore_thread_signal_I2C1_EV_IRQHandler);
    loop_thread_init();
    ivory_freertos_task_create(loop_thread_signal_I2C1_ER_IRQHandler, (uint32_t) 2560U, (uint8_t) 6U, "thread_signal_I2C1_ER_IRQHandler");
    ivory_freertos_task_create(loop_thread_signal_I2C1_EV_IRQHandler, (uint32_t) 2560U, (uint8_t) 5U, "thread_signal_I2C1_EV_IRQHandler");
    ivory_freertos_task_create(loop_thread_period_1ms, (uint32_t) 2560U, (uint8_t) 4U, "thread_period_1ms");
    ivory_freertos_task_create(loop_thread_period_20ms, (uint32_t) 2560U, (uint8_t) 3U, "thread_period_20ms");
    ivory_freertos_task_create(loop_thread_period_250ms, (uint32_t) 2560U, (uint8_t) 2U, "thread_period_250ms");
}
