/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "callback_CAN1_RX0_IRQHandler.h"

void callback_CAN1_RX0_IRQHandler(const int64_t *n_var0)
{
    emitter_CAN1_RX0_IRQHandler(n_var0);
}
