/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "simplecontroller_monitor.h"

bool tx_pending;

struct can_message last_sent;

uint32_t can_received_count = (uint32_t) 0U;

void callback_init_2(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887296U);
    
    /* reg modify rcc_apb1enr: setBit rcc_apb1en_can1 */
    ;
    
    uint32_t n_cse1 = (uint32_t) ((uint32_t) 1U << (uint32_t) 25U);
    
    ivory_hw_io_write_u32((uint32_t) 1073887296U, (uint32_t) (n_r0 | n_cse1));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073767936U);
    
    /* reg modify can->fmr: setBit can_fmr_finit, setField can_fmr_can2sb */
    ;
    
    uint32_t n_cse4 = (uint32_t) ((uint32_t) 1U << 0);
    
    ivory_hw_io_write_u32((uint32_t) 1073767936U, (uint32_t) ((uint32_t) ((uint32_t) (n_r1 | n_cse4) & (uint32_t) ~(uint32_t) ((uint32_t) 63U << (uint32_t) 8U)) | (uint32_t) ((uint32_t) 1U << (uint32_t) 8U)));
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073767964U);
    
    /* reg modify can->fa1r: clearBit can_fa1r_fact.[0], clearBit can_fa1r_fact.[1], clearBit can_fa1r_fact.[2], clearBit can_fa1r_fact.[3], clearBit can_fa1r_fact.[4], clearBit can_fa1r_fact.[5], clearBit can_fa1r_fact.[6], clearBit can_fa1r_fact.[7], clearBit can_fa1r_fact.[8], clearBit can_fa1r_fact.[9], clearBit can_fa1r_fact.[10], clearBit can_fa1r_fact.[11], clearBit can_fa1r_fact.[12], clearBit can_fa1r_fact.[13], clearBit can_fa1r_fact.[14], clearBit can_fa1r_fact.[15], clearBit can_fa1r_fact.[16], clearBit can_fa1r_fact.[17], clearBit can_fa1r_fact.[18], clearBit can_fa1r_fact.[19], clearBit can_fa1r_fact.[20], clearBit can_fa1r_fact.[21], clearBit can_fa1r_fact.[22], clearBit can_fa1r_fact.[23], clearBit can_fa1r_fact.[24], clearBit can_fa1r_fact.[25], clearBit can_fa1r_fact.[26], clearBit can_fa1r_fact.[27] */
    ;
    
    uint32_t n_cse14 = (uint32_t) ~n_cse4;
    uint32_t n_cse17 = (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 1U);
    uint32_t n_cse20 = (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 2U);
    uint32_t n_cse25 = (uint32_t) ((uint32_t) 1U << (uint32_t) 4U);
    uint32_t n_cse50 = (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 12U);
    
    ivory_hw_io_write_u32((uint32_t) 1073767964U, (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) (n_r2 &
                                                                                                                                                                                                                                                                                                                                                                                                  n_cse14) &
                                                                                                                                                                                                                                                                                                                                                                                      n_cse17) & n_cse20) &
                                                                                                                                                                                                                                                                                                                                                              (uint32_t) ~(uint32_t) ((uint32_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                      (uint32_t) 3U)) &
                                                                                                                                                                                                                                                                                                                                                  (uint32_t) ~n_cse25) &
                                                                                                                                                                                                                                                                                                                                      (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 5U)) &
                                                                                                                                                                                                                                                                                                                          (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 6U)) &
                                                                                                                                                                                                                                                                                                              (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 7U)) &
                                                                                                                                                                                                                                                                                                  (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 8U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                     (uint32_t) 9U)) &
                                                                                                                                                                                                                                                                          (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 10U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 11U)) & n_cse50) &
                                                                                                                                                                                                                                      (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 13U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 14U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U <<
                                                                                                                                                                                                                                                                                                                                                                                      (uint32_t) 15U)) &
                                                                                                                                                                                                  (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 16U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 17U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 18U)) &
                                                                                                                                                              (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 19U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 20U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 21U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 22U)) &
                                                                                                              (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 23U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 24U)) & (uint32_t) ~n_cse1) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 26U)) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 27U)));
    /* reg set can->f0r032: setField can_firx32_stid, setField can_firx32_exid, clearBit can_firx32_ide, clearBit can_firx32_rtr */
    ;
    
    uint32_t n_cse111 = (uint32_t) ((uint32_t) (n_cse17 & n_cse20) & (uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 0 << (uint32_t) 21U) & (uint32_t) ~(uint32_t) ((uint32_t) 262143U << (uint32_t) 3U)) | (uint32_t) (0 << (uint32_t) 3U)));
    
    ivory_hw_io_write_u32((uint32_t) 1073768000U, n_cse111);
    /* reg set can->f0r132: setField can_firx32_stid, setField can_firx32_exid, clearBit can_firx32_ide, clearBit can_firx32_rtr */
    ivory_hw_io_write_u32((uint32_t) 1073768004U, n_cse111);
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073767940U);
    
    /* reg modify can->fm1r: clearBit can_fm1r_fbm.[0] */
    ivory_hw_io_write_u32((uint32_t) 1073767940U, (uint32_t) (n_cse14 & n_r3));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073767956U);
    
    /* reg modify can->ffa1r: clearBit can_ffa1r_ffa.[0] */
    ivory_hw_io_write_u32((uint32_t) 1073767956U, (uint32_t) (n_cse14 & n_r4));
    
    uint32_t n_r5 = ivory_hw_io_read_u32((uint32_t) 1073767948U);
    
    /* reg modify can->fs1r: setBit can_fs1r_fsc.[0] */
    ivory_hw_io_write_u32((uint32_t) 1073767948U, (uint32_t) (n_cse4 | n_r5));
    
    uint32_t n_r6 = ivory_hw_io_read_u32((uint32_t) 1073767964U);
    
    /* reg modify can->fa1r: setBit can_fa1r_fact.[0] */
    ivory_hw_io_write_u32((uint32_t) 1073767964U, (uint32_t) (n_cse4 | n_r6));
    
    uint32_t n_r7 = ivory_hw_io_read_u32((uint32_t) 1073767936U);
    
    /* reg modify can->fmr: clearBit can_fmr_finit */
    ivory_hw_io_write_u32((uint32_t) 1073767936U, (uint32_t) (n_cse14 & n_r7));
    
    uint32_t n_r8 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_cse25 | n_r8));
    
    uint32_t n_r9 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) (n_cse50 & n_r9) | (uint32_t) (0 << (uint32_t) 12U)));
    
    uint32_t n_r10 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_12 */
    ;
    
    uint32_t n_cse131 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U);
    uint32_t n_cse133 = (uint32_t) (0 << (uint32_t) 24U);
    
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) ((uint32_t) (n_r10 & n_cse131) | n_cse133));
    
    uint32_t n_r11 = ivory_hw_io_read_u32((uint32_t) 1073877004U);
    
    /* reg modify gpioE->pupd: setField gpio_pupd_12 */
    ivory_hw_io_write_u32((uint32_t) 1073877004U, (uint32_t) (n_cse133 | (uint32_t) (n_cse131 & n_r11)));
    
    uint32_t n_r12 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_cse131 & n_r12) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
    
    uint32_t n_r13 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
    
    /* reg modify gpioE->bsrr: setBit gpio_br_12 */
    ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r13 | (uint32_t) ((uint32_t) 1U << (uint32_t) 28U)));
    
    uint32_t n_r14 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_cse131 & n_r14) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 1U << 0) << (uint32_t) 24U)));
}

void callback_periodic(const int64_t *n_var0)
{
    int64_t n_deref0 = *n_var0;
    uint64_t n_cse21 = (uint64_t) ((bool) (n_deref0 > (int64_t) 0) ? (uint64_t) n_deref0 : 0);
    struct can_message n_local1 = {.can_message_id =(uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) ((uint32_t) 2047U << (uint32_t) 18U) & (uint32_t) 536870911U) << (uint32_t) 2U) & (uint32_t) ~(uint32_t) ((uint32_t) 1U << 0)) | (uint32_t) ((uint32_t) 0 << 0)), .can_message_buf ={(uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 56U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 48U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 40U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 32U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 24U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 16U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> (uint64_t) 8U) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U),
                                                                                                                                                                                                                                                                                                    (uint8_t) (uint16_t) ((uint16_t) (uint32_t) ((uint32_t) (uint64_t) ((uint64_t) (n_cse21 >> 0) &
                                                                                                                                                                                                                                                                                                                                                                        (uint64_t) 4294967295U) &
                                                                                                                                                                                                                                                                                                                                                 (uint32_t) 65535U) & (uint16_t) 255U)}, .can_message_len =
                                   (int32_t) 8};
    struct can_message *n_ref2 = &n_local1;
    
    last_sent = *n_ref2;
    
    bool n_deref3 = tx_pending;
    
    if (n_deref3) {
        bool n_local4 = true;
        bool *n_ref5 = &n_local4;
        
        emitter_periodic_chan_4(n_ref5);
    } else {
        emitter_periodic_chan_2(&last_sent);
        tx_pending = true;
    }
}

void callback_tx_complete(const bool *n_var0)
{
    bool n_deref0 = *n_var0;
    
    if (n_deref0) {
        tx_pending = false;
    } else {
        emitter_tx_complete_chan_2(&last_sent);
        tx_pending = true;
    }
}

void callback_result(const struct can_message *n_var0)
{
    uint32_t n_deref0 = can_received_count;
    
    can_received_count = (uint32_t) (n_deref0 + (uint32_t) 1U);
    if ((bool) (0 == (uint32_t) (n_deref0 & (uint32_t) 1U))) {
        uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r1 & (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U)) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
    } else {
        uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
        
        /* reg modify gpioE->bsrr: setBit gpio_br_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r2 | (uint32_t) ((uint32_t) 1U << (uint32_t) 28U)));
        
        uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) ((uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U) & n_r3) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 1U << 0) << (uint32_t) 24U)));
    }
}
