sudo: false
language: c

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
      addons: {apt: {packages: [ghc-7.10.3,libev-dev], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.2.yaml
      addons: {apt: {packages: [ghc-8.0.2,libev-dev], sources: [hvr-ghc]}}

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
  - ghc --version
  - stack --version
install:
  - git clone https://github.com/galoisinc/ivory
  - (cd ivory; git checkout $TRAVIS_BRANCH)
  - export IVORY_REPO=$PWD/ivory
  - git clone https://github.com/galoisinc/tower
  - (cd tower; git checkout $TRAVIS_BRANCH)
  - export TOWER_REPO=$PWD/tower
  # tweak the relative paths in stack.yaml
  - sed -i "s;\.\./;$PWD/;g" $STACK_YAML
script:
  - make travis-test
