/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_USER_THREAD_INIT_H__
#define __TOWER_USER_THREAD_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_gen_thread_init.h"
#include "tower_time.h"

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_USER_THREAD_INIT_H__ */
