/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#ifndef __TOWER_GEN_THREAD_PERIOD_1MS_H__
#define __TOWER_GEN_THREAD_PERIOD_1MS_H__
#ifdef __cplusplus
extern "C" {
#endif
#include "ivory.h"
#include "tower_user_thread_period_1ms.h"
#include "tower_gen_monitor_m1.h"
#include "tower_gen_monitor_m2.h"
#include <freertos_task_wrapper.h>
#include <freertos_time_wrapper.h>
void loop_thread_period_1ms(struct taskarg *n_var0);
void emitter_tick_chan_1_thread_period_1ms_emit(const int64_t *n_var0);

#ifdef __cplusplus
}
#endif
#endif /* __TOWER_GEN_THREAD_PERIOD_1MS_H__ */
