/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_m1.h"

struct mutex lock_m1;

void monitor_init_m1(void)
{
    ivory_freertos_mutex_create(&lock_m1);
}

void monitor_lock_m1(void)
{
    ivory_freertos_mutex_takeblocking(&lock_m1);
}

void monitor_unlock_m1(void)
{
    ivory_freertos_mutex_give(&lock_m1);
}
