/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_1ms.h"

static void emitter_tick_chan_1(const int64_t *n_var0);

void callback_chan1msg_thread_period_1ms(const int64_t *n_var0)
{
    last_m2_chan1_message = *n_var0;
}

void callback_tick_thread_period_1ms(const int64_t *n_var0)
{
    last_m1_tick_message = *n_var0;
    emitter_tick_chan_1(n_var0);
}

void emitter_tick_chan_1(const int64_t *n_var0)
{
    emitter_tick_chan_1_thread_period_1ms_emit(n_var0);
}
