/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_blinker.h"

struct mutex lock_blinker;

void monitor_init_blinker(void)
{
    ivory_freertos_mutex_create(&lock_blinker);
}

void monitor_lock_blinker(void)
{
    ivory_freertos_mutex_takeblocking(&lock_blinker);
}

void monitor_unlock_blinker(void)
{
    ivory_freertos_mutex_give(&lock_blinker);
}
