/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_gen_monitor_led_2.h"

struct mutex lock_led_2;

void monitor_init_led_2(void)
{
    ivory_freertos_mutex_create(&lock_led_2);
}

void monitor_lock_led_2(void)
{
    ivory_freertos_mutex_takeblocking(&lock_led_2);
}

void monitor_unlock_led_2(void)
{
    ivory_freertos_mutex_give(&lock_led_2);
}
