/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_period_250ms.h"

static void emitter_per_chan_1(const bool *n_var0);

void callback_newoutput_thread_period_250ms(const bool *n_var0)
{
    bool n_deref0 = *n_var0;
    
    if (n_deref0) {
        uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073877016U);
        
        /* reg modify gpioE->bsrr: setBit gpio_br_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073877016U, (uint32_t) (n_r1 | (uint32_t) ((uint32_t) 1U << (uint32_t) 28U)));
        
        uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_r2 & (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U)) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 1U << 0) << (uint32_t) 24U)));
    } else {
        uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
        
        /* reg modify gpioE->mode: setField gpio_mode_12 */
        ;
        ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) ((uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U) & n_r3) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
    }
}

void callback_per_thread_period_250ms(const int64_t *n_var0)
{
    int64_t n_deref0 = *n_var0;
    int64_t n_cse1 = (int64_t) (n_deref0 % (int64_t) 500000);
    bool n_local1 = (bool) ((int64_t) ((bool) (n_cse1 < (int64_t) 0) ? (int64_t) (n_cse1 + (int64_t) 500000) : n_cse1) < (int64_t) 250000);
    bool *n_ref2 = &n_local1;
    
    emitter_per_chan_1(n_ref2);
}

void emitter_per_chan_1(const bool *n_var0)
{
    emitter_per_chan_1_thread_period_250ms_emit(n_var0);
}
