/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.5
 */
#include "tower_user_thread_init.h"

void callback_hardwareinit_2_thread_init(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpiod */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_r0 | (uint32_t) ((uint32_t) 1U << (uint32_t) 3U)));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073875972U);
    
    /* reg modify gpioD->otype: setField gpio_otype_4 */
    ivory_hw_io_write_u32((uint32_t) 1073875972U, (uint32_t) ((uint32_t) (n_r1 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 4U)) | (uint32_t) (0 << (uint32_t) 4U)));
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073875976U);
    
    /* reg modify gpioD->ospeed: setField gpio_ospeed_4 */
    ;
    
    uint32_t n_cse12 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 8U);
    uint32_t n_cse14 = (uint32_t) (0 << (uint32_t) 8U);
    
    ivory_hw_io_write_u32((uint32_t) 1073875976U, (uint32_t) ((uint32_t) (n_r2 & n_cse12) | n_cse14));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073875980U);
    
    /* reg modify gpioD->pupd: setField gpio_pupd_4 */
    ivory_hw_io_write_u32((uint32_t) 1073875980U, (uint32_t) (n_cse14 | (uint32_t) (n_cse12 & n_r3)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073875968U);
    
    /* reg modify gpioD->mode: setField gpio_mode_4 */
    ivory_hw_io_write_u32((uint32_t) 1073875968U, (uint32_t) ((uint32_t) (n_cse12 & n_r4) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 8U)));
}

void callback_hardwareinit_thread_init(const int64_t *n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887280U);
    
    /* reg modify rcc_ahb1enr: setBit rcc_ahb1en_gpioe */
    ivory_hw_io_write_u32((uint32_t) 1073887280U, (uint32_t) (n_r0 | (uint32_t) ((uint32_t) 1U << (uint32_t) 4U)));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073876996U);
    
    /* reg modify gpioE->otype: setField gpio_otype_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876996U, (uint32_t) ((uint32_t) (n_r1 & (uint32_t) ~(uint32_t) ((uint32_t) 1U << (uint32_t) 12U)) | (uint32_t) (0 << (uint32_t) 12U)));
    
    uint32_t n_r2 = ivory_hw_io_read_u32((uint32_t) 1073877000U);
    
    /* reg modify gpioE->ospeed: setField gpio_ospeed_12 */
    ;
    
    uint32_t n_cse12 = (uint32_t) ~(uint32_t) ((uint32_t) 3U << (uint32_t) 24U);
    uint32_t n_cse14 = (uint32_t) (0 << (uint32_t) 24U);
    
    ivory_hw_io_write_u32((uint32_t) 1073877000U, (uint32_t) ((uint32_t) (n_r2 & n_cse12) | n_cse14));
    
    uint32_t n_r3 = ivory_hw_io_read_u32((uint32_t) 1073877004U);
    
    /* reg modify gpioE->pupd: setField gpio_pupd_12 */
    ivory_hw_io_write_u32((uint32_t) 1073877004U, (uint32_t) (n_cse14 | (uint32_t) (n_cse12 & n_r3)));
    
    uint32_t n_r4 = ivory_hw_io_read_u32((uint32_t) 1073876992U);
    
    /* reg modify gpioE->mode: setField gpio_mode_12 */
    ivory_hw_io_write_u32((uint32_t) 1073876992U, (uint32_t) ((uint32_t) (n_cse12 & n_r4) | (uint32_t) ((uint32_t) (uint8_t) ((uint8_t) 3U << 0) << (uint32_t) 24U)));
}
